// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.26.0
// source: openmeeting/meeting/meeting.proto

package meeting

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeetingService_BookMeeting_FullMethodName                      = "/openmeeting.meeting.MeetingService/BookMeeting"
	MeetingService_CreateImmediateMeeting_FullMethodName           = "/openmeeting.meeting.MeetingService/CreateImmediateMeeting"
	MeetingService_JoinMeeting_FullMethodName                      = "/openmeeting.meeting.MeetingService/JoinMeeting"
	MeetingService_GetMeetingToken_FullMethodName                  = "/openmeeting.meeting.MeetingService/GetMeetingToken"
	MeetingService_LeaveMeeting_FullMethodName                     = "/openmeeting.meeting.MeetingService/LeaveMeeting"
	MeetingService_EndMeeting_FullMethodName                       = "/openmeeting.meeting.MeetingService/EndMeeting"
	MeetingService_GetMeetings_FullMethodName                      = "/openmeeting.meeting.MeetingService/GetMeetings"
	MeetingService_GetMeeting_FullMethodName                       = "/openmeeting.meeting.MeetingService/GetMeeting"
	MeetingService_GetMeetingAttendance_FullMethodName             = "/openmeeting.meeting.MeetingService/GetMeetingAttendance"
	MeetingService_UpdateMeeting_FullMethodName                    = "/openmeeting.meeting.MeetingService/UpdateMeeting"
	MeetingService_InviteMeetingInvitees_FullMethodName            = "/openmeeting.meeting.MeetingService/InviteMeetingInvitees"
	MeetingService_GetPersonalMeetingSettings_FullMethodName       = "/openmeeting.meeting.MeetingService/GetPersonalMeetingSettings"
	MeetingService_SetPersonalMeetingSettings_FullMethodName       = "/openmeeting.meeting.MeetingService/SetPersonalMeetingSettings"
	MeetingService_OperateRoomAllStream_FullMethodName             = "/openmeeting.meeting.MeetingService/OperateRoomAllStream"
	MeetingService_ModifyMeetingParticipantNickName_FullMethodName = "/openmeeting.meeting.MeetingService/ModifyMeetingParticipantNickName"
	MeetingService_RemoveParticipants_FullMethodName               = "/openmeeting.meeting.MeetingService/RemoveParticipants"
	MeetingService_SetMeetingHostInfo_FullMethodName               = "/openmeeting.meeting.MeetingService/SetMeetingHostInfo"
	MeetingService_CleanPreviousMeetings_FullMethodName            = "/openmeeting.meeting.MeetingService/CleanPreviousMeetings"
	MeetingService_GetMeetingRecords_FullMethodName                = "/openmeeting.meeting.MeetingService/GetMeetingRecords"
	MeetingService_GetMeetingRecordsByMeetingIDs_FullMethodName    = "/openmeeting.meeting.MeetingService/GetMeetingRecordsByMeetingIDs"
	MeetingService_GetUserMeetingHistories_FullMethodName          = "/openmeeting.meeting.MeetingService/GetUserMeetingHistories"
	MeetingService_GetUserHostedMeetings_FullMethodName            = "/openmeeting.meeting.MeetingService/GetUserHostedMeetings"
	MeetingService_DeleteMeetingRecords_FullMethodName             = "/openmeeting.meeting.MeetingService/DeleteMeetingRecords"
	MeetingService_PullMeetingChat_FullMethodName                  = "/openmeeting.meeting.MeetingService/PullMeetingChat"
	MeetingService_SendMeetingChat_FullMethodName                  = "/openmeeting.meeting.MeetingService/SendMeetingChat"
	MeetingService_RevokeMeetingChat_FullMethodName                = "/openmeeting.meeting.MeetingService/RevokeMeetingChat"
	MeetingService_CreateRepeatMeeting_FullMethodName              = "/openmeeting.meeting.MeetingService/CreateRepeatMeeting"
	MeetingService_UpdateRepeatMeeting_FullMethodName              = "/openmeeting.meeting.MeetingService/UpdateRepeatMeeting"
	MeetingService_DeleteRepeatMeeting_FullMethodName              = "/openmeeting.meeting.MeetingService/DeleteRepeatMeeting"
	MeetingService_GetRepeatMeeting_FullMethodName                 = "/openmeeting.meeting.MeetingService/GetRepeatMeeting"
	MeetingService_ListRepeatMeetings_FullMethodName               = "/openmeeting.meeting.MeetingService/ListRepeatMeetings"
	MeetingService_ListRepeatMeetingInstances_FullMethodName       = "/openmeeting.meeting.MeetingService/ListRepeatMeetingInstances"
	MeetingService_GetUserRelatedMeetings_FullMethodName           = "/openmeeting.meeting.MeetingService/GetUserRelatedMeetings"
)

// MeetingServiceClient is the client API for MeetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Defines services related to meeting management.
type MeetingServiceClient interface {
	// Books a future meeting.
	BookMeeting(ctx context.Context, in *BookMeetingReq, opts ...grpc.CallOption) (*BookMeetingResp, error)
	// Creates an immediate meeting.
	CreateImmediateMeeting(ctx context.Context, in *CreateImmediateMeetingReq, opts ...grpc.CallOption) (*CreateImmediateMeetingResp, error)
	// Joins a meeting.
	JoinMeeting(ctx context.Context, in *JoinMeetingReq, opts ...grpc.CallOption) (*JoinMeetingResp, error)
	// get a specific meeting token
	GetMeetingToken(ctx context.Context, in *GetMeetingTokenReq, opts ...grpc.CallOption) (*GetMeetingTokenResp, error)
	// Leaves a meeting.
	LeaveMeeting(ctx context.Context, in *LeaveMeetingReq, opts ...grpc.CallOption) (*LeaveMeetingResp, error)
	// Ends a meeting.
	EndMeeting(ctx context.Context, in *EndMeetingReq, opts ...grpc.CallOption) (*EndMeetingResp, error)
	// Retrieves a list of meetings that the user has created or joined, filtered by status.
	GetMeetings(ctx context.Context, in *GetMeetingsReq, opts ...grpc.CallOption) (*GetMeetingsResp, error)
	// Gets detailed information about a specific meeting.
	GetMeeting(ctx context.Context, in *GetMeetingReq, opts ...grpc.CallOption) (*GetMeetingResp, error)
	// Gets joined and absent user lists for a meeting.
	GetMeetingAttendance(ctx context.Context, in *GetMeetingAttendanceReq, opts ...grpc.CallOption) (*GetMeetingAttendanceResp, error)
	// Updates specific fields of a meeting.
	UpdateMeeting(ctx context.Context, in *UpdateMeetingRequest, opts ...grpc.CallOption) (*UpdateMeetingResp, error)
	// Invite users to join a meeting.
	InviteMeetingInvitees(ctx context.Context, in *InviteMeetingInviteesReq, opts ...grpc.CallOption) (*InviteMeetingInviteesResp, error)
	// Gets personal meeting settings.
	GetPersonalMeetingSettings(ctx context.Context, in *GetPersonalMeetingSettingsReq, opts ...grpc.CallOption) (*GetPersonalMeetingSettingsResp, error)
	// Sets personal meeting settings.
	SetPersonalMeetingSettings(ctx context.Context, in *SetPersonalMeetingSettingsReq, opts ...grpc.CallOption) (*SetPersonalMeetingSettingsResp, error)
	// operate room all stream.
	OperateRoomAllStream(ctx context.Context, in *OperateRoomAllStreamReq, opts ...grpc.CallOption) (*OperateRoomAllStreamResp, error)
	// modify meeting participant nickname
	ModifyMeetingParticipantNickName(ctx context.Context, in *ModifyMeetingParticipantNickNameReq, opts ...grpc.CallOption) (*ModifyMeetingParticipantNickNameResp, error)
	// batch remove participant out of the meeting room
	RemoveParticipants(ctx context.Context, in *RemoveMeetingParticipantsReq, opts ...grpc.CallOption) (*RemoveMeetingParticipantsResp, error)
	// modify host or co host of the meeting room
	SetMeetingHostInfo(ctx context.Context, in *SetMeetingHostInfoReq, opts ...grpc.CallOption) (*SetMeetingHostInfoResp, error)
	// clean previous meetings in rtc when login
	CleanPreviousMeetings(ctx context.Context, in *CleanPreviousMeetingsReq, opts ...grpc.CallOption) (*CleanPreviousMeetingsResp, error)
	GetMeetingRecords(ctx context.Context, in *GetMeetingRecordsReq, opts ...grpc.CallOption) (*GetMeetingRecordsResp, error)
	GetMeetingRecordsByMeetingIDs(ctx context.Context, in *GetMeetingRecordsByMeetingIDsReq, opts ...grpc.CallOption) (*GetMeetingRecordsByMeetingIDsResp, error)
	GetUserMeetingHistories(ctx context.Context, in *GetUserMeetingHistoriesReq, opts ...grpc.CallOption) (*GetUserMeetingHistoriesResp, error)
	GetUserHostedMeetings(ctx context.Context, in *GetUserHostedMeetingsReq, opts ...grpc.CallOption) (*GetUserHostedMeetingsResp, error)
	DeleteMeetingRecords(ctx context.Context, in *DeleteMeetingRecordsReq, opts ...grpc.CallOption) (*DeleteMeetingRecordsResp, error)
	// Pull meeting chat messages incrementally.
	PullMeetingChat(ctx context.Context, in *PullMeetingChatReq, opts ...grpc.CallOption) (*PullMeetingChatResp, error)
	// Send a meeting chat message.
	SendMeetingChat(ctx context.Context, in *SendMeetingChatReq, opts ...grpc.CallOption) (*SendMeetingChatResp, error)
	// Revoke a meeting chat message.
	RevokeMeetingChat(ctx context.Context, in *RevokeMeetingChatReq, opts ...grpc.CallOption) (*RevokeMeetingChatResp, error)
	// Repeat meeting management
	CreateRepeatMeeting(ctx context.Context, in *CreateRepeatMeetingReq, opts ...grpc.CallOption) (*CreateRepeatMeetingResp, error)
	UpdateRepeatMeeting(ctx context.Context, in *UpdateRepeatMeetingReq, opts ...grpc.CallOption) (*UpdateRepeatMeetingResp, error)
	DeleteRepeatMeeting(ctx context.Context, in *DeleteRepeatMeetingReq, opts ...grpc.CallOption) (*DeleteRepeatMeetingResp, error)
	GetRepeatMeeting(ctx context.Context, in *GetRepeatMeetingReq, opts ...grpc.CallOption) (*GetRepeatMeetingResp, error)
	ListRepeatMeetings(ctx context.Context, in *ListRepeatMeetingsReq, opts ...grpc.CallOption) (*ListRepeatMeetingsResp, error)
	ListRepeatMeetingInstances(ctx context.Context, in *ListRepeatMeetingInstancesReq, opts ...grpc.CallOption) (*ListRepeatMeetingInstancesResp, error)
	GetUserRelatedMeetings(ctx context.Context, in *GetUserRelatedMeetingsReq, opts ...grpc.CallOption) (*GetUserRelatedMeetingsResp, error)
}

type meetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetingServiceClient(cc grpc.ClientConnInterface) MeetingServiceClient {
	return &meetingServiceClient{cc}
}

func (c *meetingServiceClient) BookMeeting(ctx context.Context, in *BookMeetingReq, opts ...grpc.CallOption) (*BookMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_BookMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) CreateImmediateMeeting(ctx context.Context, in *CreateImmediateMeetingReq, opts ...grpc.CallOption) (*CreateImmediateMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateImmediateMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_CreateImmediateMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) JoinMeeting(ctx context.Context, in *JoinMeetingReq, opts ...grpc.CallOption) (*JoinMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_JoinMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeetingToken(ctx context.Context, in *GetMeetingTokenReq, opts ...grpc.CallOption) (*GetMeetingTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingTokenResp)
	err := c.cc.Invoke(ctx, MeetingService_GetMeetingToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) LeaveMeeting(ctx context.Context, in *LeaveMeetingReq, opts ...grpc.CallOption) (*LeaveMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_LeaveMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) EndMeeting(ctx context.Context, in *EndMeetingReq, opts ...grpc.CallOption) (*EndMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_EndMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeetings(ctx context.Context, in *GetMeetingsReq, opts ...grpc.CallOption) (*GetMeetingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingsResp)
	err := c.cc.Invoke(ctx, MeetingService_GetMeetings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeeting(ctx context.Context, in *GetMeetingReq, opts ...grpc.CallOption) (*GetMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_GetMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeetingAttendance(ctx context.Context, in *GetMeetingAttendanceReq, opts ...grpc.CallOption) (*GetMeetingAttendanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingAttendanceResp)
	err := c.cc.Invoke(ctx, MeetingService_GetMeetingAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) UpdateMeeting(ctx context.Context, in *UpdateMeetingRequest, opts ...grpc.CallOption) (*UpdateMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_UpdateMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) InviteMeetingInvitees(ctx context.Context, in *InviteMeetingInviteesReq, opts ...grpc.CallOption) (*InviteMeetingInviteesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMeetingInviteesResp)
	err := c.cc.Invoke(ctx, MeetingService_InviteMeetingInvitees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetPersonalMeetingSettings(ctx context.Context, in *GetPersonalMeetingSettingsReq, opts ...grpc.CallOption) (*GetPersonalMeetingSettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPersonalMeetingSettingsResp)
	err := c.cc.Invoke(ctx, MeetingService_GetPersonalMeetingSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) SetPersonalMeetingSettings(ctx context.Context, in *SetPersonalMeetingSettingsReq, opts ...grpc.CallOption) (*SetPersonalMeetingSettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPersonalMeetingSettingsResp)
	err := c.cc.Invoke(ctx, MeetingService_SetPersonalMeetingSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) OperateRoomAllStream(ctx context.Context, in *OperateRoomAllStreamReq, opts ...grpc.CallOption) (*OperateRoomAllStreamResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateRoomAllStreamResp)
	err := c.cc.Invoke(ctx, MeetingService_OperateRoomAllStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) ModifyMeetingParticipantNickName(ctx context.Context, in *ModifyMeetingParticipantNickNameReq, opts ...grpc.CallOption) (*ModifyMeetingParticipantNickNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyMeetingParticipantNickNameResp)
	err := c.cc.Invoke(ctx, MeetingService_ModifyMeetingParticipantNickName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) RemoveParticipants(ctx context.Context, in *RemoveMeetingParticipantsReq, opts ...grpc.CallOption) (*RemoveMeetingParticipantsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMeetingParticipantsResp)
	err := c.cc.Invoke(ctx, MeetingService_RemoveParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) SetMeetingHostInfo(ctx context.Context, in *SetMeetingHostInfoReq, opts ...grpc.CallOption) (*SetMeetingHostInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMeetingHostInfoResp)
	err := c.cc.Invoke(ctx, MeetingService_SetMeetingHostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) CleanPreviousMeetings(ctx context.Context, in *CleanPreviousMeetingsReq, opts ...grpc.CallOption) (*CleanPreviousMeetingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanPreviousMeetingsResp)
	err := c.cc.Invoke(ctx, MeetingService_CleanPreviousMeetings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeetingRecords(ctx context.Context, in *GetMeetingRecordsReq, opts ...grpc.CallOption) (*GetMeetingRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingRecordsResp)
	err := c.cc.Invoke(ctx, MeetingService_GetMeetingRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeetingRecordsByMeetingIDs(ctx context.Context, in *GetMeetingRecordsByMeetingIDsReq, opts ...grpc.CallOption) (*GetMeetingRecordsByMeetingIDsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingRecordsByMeetingIDsResp)
	err := c.cc.Invoke(ctx, MeetingService_GetMeetingRecordsByMeetingIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetUserMeetingHistories(ctx context.Context, in *GetUserMeetingHistoriesReq, opts ...grpc.CallOption) (*GetUserMeetingHistoriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMeetingHistoriesResp)
	err := c.cc.Invoke(ctx, MeetingService_GetUserMeetingHistories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetUserHostedMeetings(ctx context.Context, in *GetUserHostedMeetingsReq, opts ...grpc.CallOption) (*GetUserHostedMeetingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserHostedMeetingsResp)
	err := c.cc.Invoke(ctx, MeetingService_GetUserHostedMeetings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) DeleteMeetingRecords(ctx context.Context, in *DeleteMeetingRecordsReq, opts ...grpc.CallOption) (*DeleteMeetingRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMeetingRecordsResp)
	err := c.cc.Invoke(ctx, MeetingService_DeleteMeetingRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) PullMeetingChat(ctx context.Context, in *PullMeetingChatReq, opts ...grpc.CallOption) (*PullMeetingChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullMeetingChatResp)
	err := c.cc.Invoke(ctx, MeetingService_PullMeetingChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) SendMeetingChat(ctx context.Context, in *SendMeetingChatReq, opts ...grpc.CallOption) (*SendMeetingChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMeetingChatResp)
	err := c.cc.Invoke(ctx, MeetingService_SendMeetingChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) RevokeMeetingChat(ctx context.Context, in *RevokeMeetingChatReq, opts ...grpc.CallOption) (*RevokeMeetingChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeMeetingChatResp)
	err := c.cc.Invoke(ctx, MeetingService_RevokeMeetingChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) CreateRepeatMeeting(ctx context.Context, in *CreateRepeatMeetingReq, opts ...grpc.CallOption) (*CreateRepeatMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRepeatMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_CreateRepeatMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) UpdateRepeatMeeting(ctx context.Context, in *UpdateRepeatMeetingReq, opts ...grpc.CallOption) (*UpdateRepeatMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRepeatMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_UpdateRepeatMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) DeleteRepeatMeeting(ctx context.Context, in *DeleteRepeatMeetingReq, opts ...grpc.CallOption) (*DeleteRepeatMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRepeatMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_DeleteRepeatMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetRepeatMeeting(ctx context.Context, in *GetRepeatMeetingReq, opts ...grpc.CallOption) (*GetRepeatMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepeatMeetingResp)
	err := c.cc.Invoke(ctx, MeetingService_GetRepeatMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) ListRepeatMeetings(ctx context.Context, in *ListRepeatMeetingsReq, opts ...grpc.CallOption) (*ListRepeatMeetingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepeatMeetingsResp)
	err := c.cc.Invoke(ctx, MeetingService_ListRepeatMeetings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) ListRepeatMeetingInstances(ctx context.Context, in *ListRepeatMeetingInstancesReq, opts ...grpc.CallOption) (*ListRepeatMeetingInstancesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepeatMeetingInstancesResp)
	err := c.cc.Invoke(ctx, MeetingService_ListRepeatMeetingInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetUserRelatedMeetings(ctx context.Context, in *GetUserRelatedMeetingsReq, opts ...grpc.CallOption) (*GetUserRelatedMeetingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRelatedMeetingsResp)
	err := c.cc.Invoke(ctx, MeetingService_GetUserRelatedMeetings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetingServiceServer is the server API for MeetingService service.
// All implementations must embed UnimplementedMeetingServiceServer
// for forward compatibility.
//
// Defines services related to meeting management.
type MeetingServiceServer interface {
	// Books a future meeting.
	BookMeeting(context.Context, *BookMeetingReq) (*BookMeetingResp, error)
	// Creates an immediate meeting.
	CreateImmediateMeeting(context.Context, *CreateImmediateMeetingReq) (*CreateImmediateMeetingResp, error)
	// Joins a meeting.
	JoinMeeting(context.Context, *JoinMeetingReq) (*JoinMeetingResp, error)
	// get a specific meeting token
	GetMeetingToken(context.Context, *GetMeetingTokenReq) (*GetMeetingTokenResp, error)
	// Leaves a meeting.
	LeaveMeeting(context.Context, *LeaveMeetingReq) (*LeaveMeetingResp, error)
	// Ends a meeting.
	EndMeeting(context.Context, *EndMeetingReq) (*EndMeetingResp, error)
	// Retrieves a list of meetings that the user has created or joined, filtered by status.
	GetMeetings(context.Context, *GetMeetingsReq) (*GetMeetingsResp, error)
	// Gets detailed information about a specific meeting.
	GetMeeting(context.Context, *GetMeetingReq) (*GetMeetingResp, error)
	// Gets joined and absent user lists for a meeting.
	GetMeetingAttendance(context.Context, *GetMeetingAttendanceReq) (*GetMeetingAttendanceResp, error)
	// Updates specific fields of a meeting.
	UpdateMeeting(context.Context, *UpdateMeetingRequest) (*UpdateMeetingResp, error)
	// Invite users to join a meeting.
	InviteMeetingInvitees(context.Context, *InviteMeetingInviteesReq) (*InviteMeetingInviteesResp, error)
	// Gets personal meeting settings.
	GetPersonalMeetingSettings(context.Context, *GetPersonalMeetingSettingsReq) (*GetPersonalMeetingSettingsResp, error)
	// Sets personal meeting settings.
	SetPersonalMeetingSettings(context.Context, *SetPersonalMeetingSettingsReq) (*SetPersonalMeetingSettingsResp, error)
	// operate room all stream.
	OperateRoomAllStream(context.Context, *OperateRoomAllStreamReq) (*OperateRoomAllStreamResp, error)
	// modify meeting participant nickname
	ModifyMeetingParticipantNickName(context.Context, *ModifyMeetingParticipantNickNameReq) (*ModifyMeetingParticipantNickNameResp, error)
	// batch remove participant out of the meeting room
	RemoveParticipants(context.Context, *RemoveMeetingParticipantsReq) (*RemoveMeetingParticipantsResp, error)
	// modify host or co host of the meeting room
	SetMeetingHostInfo(context.Context, *SetMeetingHostInfoReq) (*SetMeetingHostInfoResp, error)
	// clean previous meetings in rtc when login
	CleanPreviousMeetings(context.Context, *CleanPreviousMeetingsReq) (*CleanPreviousMeetingsResp, error)
	GetMeetingRecords(context.Context, *GetMeetingRecordsReq) (*GetMeetingRecordsResp, error)
	GetMeetingRecordsByMeetingIDs(context.Context, *GetMeetingRecordsByMeetingIDsReq) (*GetMeetingRecordsByMeetingIDsResp, error)
	GetUserMeetingHistories(context.Context, *GetUserMeetingHistoriesReq) (*GetUserMeetingHistoriesResp, error)
	GetUserHostedMeetings(context.Context, *GetUserHostedMeetingsReq) (*GetUserHostedMeetingsResp, error)
	DeleteMeetingRecords(context.Context, *DeleteMeetingRecordsReq) (*DeleteMeetingRecordsResp, error)
	// Pull meeting chat messages incrementally.
	PullMeetingChat(context.Context, *PullMeetingChatReq) (*PullMeetingChatResp, error)
	// Send a meeting chat message.
	SendMeetingChat(context.Context, *SendMeetingChatReq) (*SendMeetingChatResp, error)
	// Revoke a meeting chat message.
	RevokeMeetingChat(context.Context, *RevokeMeetingChatReq) (*RevokeMeetingChatResp, error)
	// Repeat meeting management
	CreateRepeatMeeting(context.Context, *CreateRepeatMeetingReq) (*CreateRepeatMeetingResp, error)
	UpdateRepeatMeeting(context.Context, *UpdateRepeatMeetingReq) (*UpdateRepeatMeetingResp, error)
	DeleteRepeatMeeting(context.Context, *DeleteRepeatMeetingReq) (*DeleteRepeatMeetingResp, error)
	GetRepeatMeeting(context.Context, *GetRepeatMeetingReq) (*GetRepeatMeetingResp, error)
	ListRepeatMeetings(context.Context, *ListRepeatMeetingsReq) (*ListRepeatMeetingsResp, error)
	ListRepeatMeetingInstances(context.Context, *ListRepeatMeetingInstancesReq) (*ListRepeatMeetingInstancesResp, error)
	GetUserRelatedMeetings(context.Context, *GetUserRelatedMeetingsReq) (*GetUserRelatedMeetingsResp, error)
	mustEmbedUnimplementedMeetingServiceServer()
}

// UnimplementedMeetingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeetingServiceServer struct{}

func (UnimplementedMeetingServiceServer) BookMeeting(context.Context, *BookMeetingReq) (*BookMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BookMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) CreateImmediateMeeting(context.Context, *CreateImmediateMeetingReq) (*CreateImmediateMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImmediateMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) JoinMeeting(context.Context, *JoinMeetingReq) (*JoinMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeetingToken(context.Context, *GetMeetingTokenReq) (*GetMeetingTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetingToken not implemented")
}
func (UnimplementedMeetingServiceServer) LeaveMeeting(context.Context, *LeaveMeetingReq) (*LeaveMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) EndMeeting(context.Context, *EndMeetingReq) (*EndMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EndMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeetings(context.Context, *GetMeetingsReq) (*GetMeetingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetings not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeeting(context.Context, *GetMeetingReq) (*GetMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeetingAttendance(context.Context, *GetMeetingAttendanceReq) (*GetMeetingAttendanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetingAttendance not implemented")
}
func (UnimplementedMeetingServiceServer) UpdateMeeting(context.Context, *UpdateMeetingRequest) (*UpdateMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) InviteMeetingInvitees(context.Context, *InviteMeetingInviteesReq) (*InviteMeetingInviteesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMeetingInvitees not implemented")
}
func (UnimplementedMeetingServiceServer) GetPersonalMeetingSettings(context.Context, *GetPersonalMeetingSettingsReq) (*GetPersonalMeetingSettingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPersonalMeetingSettings not implemented")
}
func (UnimplementedMeetingServiceServer) SetPersonalMeetingSettings(context.Context, *SetPersonalMeetingSettingsReq) (*SetPersonalMeetingSettingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPersonalMeetingSettings not implemented")
}
func (UnimplementedMeetingServiceServer) OperateRoomAllStream(context.Context, *OperateRoomAllStreamReq) (*OperateRoomAllStreamResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OperateRoomAllStream not implemented")
}
func (UnimplementedMeetingServiceServer) ModifyMeetingParticipantNickName(context.Context, *ModifyMeetingParticipantNickNameReq) (*ModifyMeetingParticipantNickNameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyMeetingParticipantNickName not implemented")
}
func (UnimplementedMeetingServiceServer) RemoveParticipants(context.Context, *RemoveMeetingParticipantsReq) (*RemoveMeetingParticipantsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveParticipants not implemented")
}
func (UnimplementedMeetingServiceServer) SetMeetingHostInfo(context.Context, *SetMeetingHostInfoReq) (*SetMeetingHostInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMeetingHostInfo not implemented")
}
func (UnimplementedMeetingServiceServer) CleanPreviousMeetings(context.Context, *CleanPreviousMeetingsReq) (*CleanPreviousMeetingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanPreviousMeetings not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeetingRecords(context.Context, *GetMeetingRecordsReq) (*GetMeetingRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetingRecords not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeetingRecordsByMeetingIDs(context.Context, *GetMeetingRecordsByMeetingIDsReq) (*GetMeetingRecordsByMeetingIDsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetingRecordsByMeetingIDs not implemented")
}
func (UnimplementedMeetingServiceServer) GetUserMeetingHistories(context.Context, *GetUserMeetingHistoriesReq) (*GetUserMeetingHistoriesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMeetingHistories not implemented")
}
func (UnimplementedMeetingServiceServer) GetUserHostedMeetings(context.Context, *GetUserHostedMeetingsReq) (*GetUserHostedMeetingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserHostedMeetings not implemented")
}
func (UnimplementedMeetingServiceServer) DeleteMeetingRecords(context.Context, *DeleteMeetingRecordsReq) (*DeleteMeetingRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMeetingRecords not implemented")
}
func (UnimplementedMeetingServiceServer) PullMeetingChat(context.Context, *PullMeetingChatReq) (*PullMeetingChatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PullMeetingChat not implemented")
}
func (UnimplementedMeetingServiceServer) SendMeetingChat(context.Context, *SendMeetingChatReq) (*SendMeetingChatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMeetingChat not implemented")
}
func (UnimplementedMeetingServiceServer) RevokeMeetingChat(context.Context, *RevokeMeetingChatReq) (*RevokeMeetingChatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeMeetingChat not implemented")
}
func (UnimplementedMeetingServiceServer) CreateRepeatMeeting(context.Context, *CreateRepeatMeetingReq) (*CreateRepeatMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRepeatMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) UpdateRepeatMeeting(context.Context, *UpdateRepeatMeetingReq) (*UpdateRepeatMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepeatMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) DeleteRepeatMeeting(context.Context, *DeleteRepeatMeetingReq) (*DeleteRepeatMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRepeatMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) GetRepeatMeeting(context.Context, *GetRepeatMeetingReq) (*GetRepeatMeetingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepeatMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) ListRepeatMeetings(context.Context, *ListRepeatMeetingsReq) (*ListRepeatMeetingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepeatMeetings not implemented")
}
func (UnimplementedMeetingServiceServer) ListRepeatMeetingInstances(context.Context, *ListRepeatMeetingInstancesReq) (*ListRepeatMeetingInstancesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepeatMeetingInstances not implemented")
}
func (UnimplementedMeetingServiceServer) GetUserRelatedMeetings(context.Context, *GetUserRelatedMeetingsReq) (*GetUserRelatedMeetingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRelatedMeetings not implemented")
}
func (UnimplementedMeetingServiceServer) mustEmbedUnimplementedMeetingServiceServer() {}
func (UnimplementedMeetingServiceServer) testEmbeddedByValue()                        {}

// UnsafeMeetingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeetingServiceServer will
// result in compilation errors.
type UnsafeMeetingServiceServer interface {
	mustEmbedUnimplementedMeetingServiceServer()
}

func RegisterMeetingServiceServer(s grpc.ServiceRegistrar, srv MeetingServiceServer) {
	// If the following call panics, it indicates UnimplementedMeetingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeetingService_ServiceDesc, srv)
}

func _MeetingService_BookMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).BookMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_BookMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).BookMeeting(ctx, req.(*BookMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_CreateImmediateMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImmediateMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).CreateImmediateMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_CreateImmediateMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).CreateImmediateMeeting(ctx, req.(*CreateImmediateMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_JoinMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).JoinMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_JoinMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).JoinMeeting(ctx, req.(*JoinMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeetingToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeetingToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeetingToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeetingToken(ctx, req.(*GetMeetingTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_LeaveMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).LeaveMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_LeaveMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).LeaveMeeting(ctx, req.(*LeaveMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_EndMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).EndMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_EndMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).EndMeeting(ctx, req.(*EndMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeetings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeetings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeetings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeetings(ctx, req.(*GetMeetingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeeting(ctx, req.(*GetMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeetingAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingAttendanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeetingAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeetingAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeetingAttendance(ctx, req.(*GetMeetingAttendanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_UpdateMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).UpdateMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_UpdateMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).UpdateMeeting(ctx, req.(*UpdateMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_InviteMeetingInvitees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMeetingInviteesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).InviteMeetingInvitees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_InviteMeetingInvitees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).InviteMeetingInvitees(ctx, req.(*InviteMeetingInviteesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetPersonalMeetingSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonalMeetingSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetPersonalMeetingSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetPersonalMeetingSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetPersonalMeetingSettings(ctx, req.(*GetPersonalMeetingSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_SetPersonalMeetingSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPersonalMeetingSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).SetPersonalMeetingSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_SetPersonalMeetingSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).SetPersonalMeetingSettings(ctx, req.(*SetPersonalMeetingSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_OperateRoomAllStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateRoomAllStreamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).OperateRoomAllStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_OperateRoomAllStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).OperateRoomAllStream(ctx, req.(*OperateRoomAllStreamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_ModifyMeetingParticipantNickName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyMeetingParticipantNickNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).ModifyMeetingParticipantNickName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_ModifyMeetingParticipantNickName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).ModifyMeetingParticipantNickName(ctx, req.(*ModifyMeetingParticipantNickNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_RemoveParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMeetingParticipantsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).RemoveParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_RemoveParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).RemoveParticipants(ctx, req.(*RemoveMeetingParticipantsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_SetMeetingHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMeetingHostInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).SetMeetingHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_SetMeetingHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).SetMeetingHostInfo(ctx, req.(*SetMeetingHostInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_CleanPreviousMeetings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanPreviousMeetingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).CleanPreviousMeetings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_CleanPreviousMeetings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).CleanPreviousMeetings(ctx, req.(*CleanPreviousMeetingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeetingRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeetingRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeetingRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeetingRecords(ctx, req.(*GetMeetingRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeetingRecordsByMeetingIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingRecordsByMeetingIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeetingRecordsByMeetingIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeetingRecordsByMeetingIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeetingRecordsByMeetingIDs(ctx, req.(*GetMeetingRecordsByMeetingIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetUserMeetingHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMeetingHistoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetUserMeetingHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetUserMeetingHistories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetUserMeetingHistories(ctx, req.(*GetUserMeetingHistoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetUserHostedMeetings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserHostedMeetingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetUserHostedMeetings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetUserHostedMeetings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetUserHostedMeetings(ctx, req.(*GetUserHostedMeetingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_DeleteMeetingRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMeetingRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).DeleteMeetingRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_DeleteMeetingRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).DeleteMeetingRecords(ctx, req.(*DeleteMeetingRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_PullMeetingChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullMeetingChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).PullMeetingChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_PullMeetingChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).PullMeetingChat(ctx, req.(*PullMeetingChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_SendMeetingChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMeetingChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).SendMeetingChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_SendMeetingChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).SendMeetingChat(ctx, req.(*SendMeetingChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_RevokeMeetingChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMeetingChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).RevokeMeetingChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_RevokeMeetingChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).RevokeMeetingChat(ctx, req.(*RevokeMeetingChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_CreateRepeatMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRepeatMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).CreateRepeatMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_CreateRepeatMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).CreateRepeatMeeting(ctx, req.(*CreateRepeatMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_UpdateRepeatMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepeatMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).UpdateRepeatMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_UpdateRepeatMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).UpdateRepeatMeeting(ctx, req.(*UpdateRepeatMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_DeleteRepeatMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRepeatMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).DeleteRepeatMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_DeleteRepeatMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).DeleteRepeatMeeting(ctx, req.(*DeleteRepeatMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetRepeatMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepeatMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetRepeatMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetRepeatMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetRepeatMeeting(ctx, req.(*GetRepeatMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_ListRepeatMeetings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepeatMeetingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).ListRepeatMeetings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_ListRepeatMeetings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).ListRepeatMeetings(ctx, req.(*ListRepeatMeetingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_ListRepeatMeetingInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepeatMeetingInstancesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).ListRepeatMeetingInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_ListRepeatMeetingInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).ListRepeatMeetingInstances(ctx, req.(*ListRepeatMeetingInstancesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetUserRelatedMeetings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRelatedMeetingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetUserRelatedMeetings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetUserRelatedMeetings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetUserRelatedMeetings(ctx, req.(*GetUserRelatedMeetingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MeetingService_ServiceDesc is the grpc.ServiceDesc for MeetingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeetingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openmeeting.meeting.MeetingService",
	HandlerType: (*MeetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookMeeting",
			Handler:    _MeetingService_BookMeeting_Handler,
		},
		{
			MethodName: "CreateImmediateMeeting",
			Handler:    _MeetingService_CreateImmediateMeeting_Handler,
		},
		{
			MethodName: "JoinMeeting",
			Handler:    _MeetingService_JoinMeeting_Handler,
		},
		{
			MethodName: "GetMeetingToken",
			Handler:    _MeetingService_GetMeetingToken_Handler,
		},
		{
			MethodName: "LeaveMeeting",
			Handler:    _MeetingService_LeaveMeeting_Handler,
		},
		{
			MethodName: "EndMeeting",
			Handler:    _MeetingService_EndMeeting_Handler,
		},
		{
			MethodName: "GetMeetings",
			Handler:    _MeetingService_GetMeetings_Handler,
		},
		{
			MethodName: "GetMeeting",
			Handler:    _MeetingService_GetMeeting_Handler,
		},
		{
			MethodName: "GetMeetingAttendance",
			Handler:    _MeetingService_GetMeetingAttendance_Handler,
		},
		{
			MethodName: "UpdateMeeting",
			Handler:    _MeetingService_UpdateMeeting_Handler,
		},
		{
			MethodName: "InviteMeetingInvitees",
			Handler:    _MeetingService_InviteMeetingInvitees_Handler,
		},
		{
			MethodName: "GetPersonalMeetingSettings",
			Handler:    _MeetingService_GetPersonalMeetingSettings_Handler,
		},
		{
			MethodName: "SetPersonalMeetingSettings",
			Handler:    _MeetingService_SetPersonalMeetingSettings_Handler,
		},
		{
			MethodName: "OperateRoomAllStream",
			Handler:    _MeetingService_OperateRoomAllStream_Handler,
		},
		{
			MethodName: "ModifyMeetingParticipantNickName",
			Handler:    _MeetingService_ModifyMeetingParticipantNickName_Handler,
		},
		{
			MethodName: "RemoveParticipants",
			Handler:    _MeetingService_RemoveParticipants_Handler,
		},
		{
			MethodName: "SetMeetingHostInfo",
			Handler:    _MeetingService_SetMeetingHostInfo_Handler,
		},
		{
			MethodName: "CleanPreviousMeetings",
			Handler:    _MeetingService_CleanPreviousMeetings_Handler,
		},
		{
			MethodName: "GetMeetingRecords",
			Handler:    _MeetingService_GetMeetingRecords_Handler,
		},
		{
			MethodName: "GetMeetingRecordsByMeetingIDs",
			Handler:    _MeetingService_GetMeetingRecordsByMeetingIDs_Handler,
		},
		{
			MethodName: "GetUserMeetingHistories",
			Handler:    _MeetingService_GetUserMeetingHistories_Handler,
		},
		{
			MethodName: "GetUserHostedMeetings",
			Handler:    _MeetingService_GetUserHostedMeetings_Handler,
		},
		{
			MethodName: "DeleteMeetingRecords",
			Handler:    _MeetingService_DeleteMeetingRecords_Handler,
		},
		{
			MethodName: "PullMeetingChat",
			Handler:    _MeetingService_PullMeetingChat_Handler,
		},
		{
			MethodName: "SendMeetingChat",
			Handler:    _MeetingService_SendMeetingChat_Handler,
		},
		{
			MethodName: "RevokeMeetingChat",
			Handler:    _MeetingService_RevokeMeetingChat_Handler,
		},
		{
			MethodName: "CreateRepeatMeeting",
			Handler:    _MeetingService_CreateRepeatMeeting_Handler,
		},
		{
			MethodName: "UpdateRepeatMeeting",
			Handler:    _MeetingService_UpdateRepeatMeeting_Handler,
		},
		{
			MethodName: "DeleteRepeatMeeting",
			Handler:    _MeetingService_DeleteRepeatMeeting_Handler,
		},
		{
			MethodName: "GetRepeatMeeting",
			Handler:    _MeetingService_GetRepeatMeeting_Handler,
		},
		{
			MethodName: "ListRepeatMeetings",
			Handler:    _MeetingService_ListRepeatMeetings_Handler,
		},
		{
			MethodName: "ListRepeatMeetingInstances",
			Handler:    _MeetingService_ListRepeatMeetingInstances_Handler,
		},
		{
			MethodName: "GetUserRelatedMeetings",
			Handler:    _MeetingService_GetUserRelatedMeetings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openmeeting/meeting/meeting.proto",
}
