// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.0
// source: encryption/encryption.proto

package encryption

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_encryption_encryption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *CommonResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type MsgContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendID        string                 `protobuf:"bytes,1,opt,name=sendID,proto3" json:"sendID"`
	RecvID        string                 `protobuf:"bytes,2,opt,name=recvID,proto3" json:"recvID"`
	GroupID       string                 `protobuf:"bytes,3,opt,name=groupID,proto3" json:"groupID"`
	SessionType   int32                  `protobuf:"varint,4,opt,name=sessionType,proto3" json:"sessionType"`
	MsgFrom       int32                  `protobuf:"varint,5,opt,name=msgFrom,proto3" json:"msgFrom"`
	ContentType   int32                  `protobuf:"varint,6,opt,name=contentType,proto3" json:"contentType"`
	Content       []byte                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content"`
	KeyVersion    int32                  `protobuf:"varint,8,opt,name=keyVersion,proto3" json:"keyVersion"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgContent) Reset() {
	*x = MsgContent{}
	mi := &file_encryption_encryption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgContent) ProtoMessage() {}

func (x *MsgContent) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgContent.ProtoReflect.Descriptor instead.
func (*MsgContent) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{1}
}

func (x *MsgContent) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *MsgContent) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *MsgContent) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *MsgContent) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *MsgContent) GetMsgFrom() int32 {
	if x != nil {
		return x.MsgFrom
	}
	return 0
}

func (x *MsgContent) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *MsgContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MsgContent) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

type EncryptContentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgContent    *MsgContent            `protobuf:"bytes,1,opt,name=msgContent,proto3" json:"msgContent"`
	RecvIDList    []string               `protobuf:"bytes,2,rep,name=recvIDList,proto3" json:"recvIDList"`
	OperationID   string                 `protobuf:"bytes,3,opt,name=operationID,proto3" json:"operationID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptContentReq) Reset() {
	*x = EncryptContentReq{}
	mi := &file_encryption_encryption_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptContentReq) ProtoMessage() {}

func (x *EncryptContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptContentReq.ProtoReflect.Descriptor instead.
func (*EncryptContentReq) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptContentReq) GetMsgContent() *MsgContent {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

func (x *EncryptContentReq) GetRecvIDList() []string {
	if x != nil {
		return x.RecvIDList
	}
	return nil
}

func (x *EncryptContentReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

type EncryptContentResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommonResp     *CommonResp            `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp"`
	MsgContentList []*MsgContent          `protobuf:"bytes,2,rep,name=msgContentList,proto3" json:"msgContentList"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EncryptContentResp) Reset() {
	*x = EncryptContentResp{}
	mi := &file_encryption_encryption_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptContentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptContentResp) ProtoMessage() {}

func (x *EncryptContentResp) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptContentResp.ProtoReflect.Descriptor instead.
func (*EncryptContentResp) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptContentResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *EncryptContentResp) GetMsgContentList() []*MsgContent {
	if x != nil {
		return x.MsgContentList
	}
	return nil
}

type GetEncryptionKeyReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationID string                 `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID"`
	KeyVersion     int32                  `protobuf:"varint,2,opt,name=keyVersion,proto3" json:"keyVersion"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEncryptionKeyReq) Reset() {
	*x = GetEncryptionKeyReq{}
	mi := &file_encryption_encryption_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEncryptionKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncryptionKeyReq) ProtoMessage() {}

func (x *GetEncryptionKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncryptionKeyReq.ProtoReflect.Descriptor instead.
func (*GetEncryptionKeyReq) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{4}
}

func (x *GetEncryptionKeyReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *GetEncryptionKeyReq) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

type VersionKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionKey) Reset() {
	*x = VersionKey{}
	mi := &file_encryption_encryption_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionKey) ProtoMessage() {}

func (x *VersionKey) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionKey.ProtoReflect.Descriptor instead.
func (*VersionKey) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{5}
}

func (x *VersionKey) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetEncryptionKeyResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VersionKeyList []*VersionKey          `protobuf:"bytes,2,rep,name=versionKeyList,proto3" json:"versionKeyList"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEncryptionKeyResp) Reset() {
	*x = GetEncryptionKeyResp{}
	mi := &file_encryption_encryption_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEncryptionKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncryptionKeyResp) ProtoMessage() {}

func (x *GetEncryptionKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncryptionKeyResp.ProtoReflect.Descriptor instead.
func (*GetEncryptionKeyResp) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{6}
}

func (x *GetEncryptionKeyResp) GetVersionKeyList() []*VersionKey {
	if x != nil {
		return x.VersionKeyList
	}
	return nil
}

type GenEncryptionKeyReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationID string                 `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenEncryptionKeyReq) Reset() {
	*x = GenEncryptionKeyReq{}
	mi := &file_encryption_encryption_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenEncryptionKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenEncryptionKeyReq) ProtoMessage() {}

func (x *GenEncryptionKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenEncryptionKeyReq.ProtoReflect.Descriptor instead.
func (*GenEncryptionKeyReq) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{7}
}

func (x *GenEncryptionKeyReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

type GenEncryptionKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenEncryptionKeyResp) Reset() {
	*x = GenEncryptionKeyResp{}
	mi := &file_encryption_encryption_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenEncryptionKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenEncryptionKeyResp) ProtoMessage() {}

func (x *GenEncryptionKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenEncryptionKeyResp.ProtoReflect.Descriptor instead.
func (*GenEncryptionKeyResp) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{8}
}

type GroupVersionKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key"`
	GroupID       string                 `protobuf:"bytes,3,opt,name=groupID,proto3" json:"groupID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupVersionKey) Reset() {
	*x = GroupVersionKey{}
	mi := &file_encryption_encryption_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupVersionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupVersionKey) ProtoMessage() {}

func (x *GroupVersionKey) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupVersionKey.ProtoReflect.Descriptor instead.
func (*GroupVersionKey) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{9}
}

func (x *GroupVersionKey) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GroupVersionKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GroupVersionKey) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type DecryptContentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgContent    *MsgContent            `protobuf:"bytes,1,opt,name=msgContent,proto3" json:"msgContent"`
	OperationID   string                 `protobuf:"bytes,2,opt,name=operationID,proto3" json:"operationID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptContentReq) Reset() {
	*x = DecryptContentReq{}
	mi := &file_encryption_encryption_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptContentReq) ProtoMessage() {}

func (x *DecryptContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptContentReq.ProtoReflect.Descriptor instead.
func (*DecryptContentReq) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{10}
}

func (x *DecryptContentReq) GetMsgContent() *MsgContent {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

func (x *DecryptContentReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

type DecryptContentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonResp    *CommonResp            `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp"`
	MsgContent    *MsgContent            `protobuf:"bytes,2,opt,name=msgContent,proto3" json:"msgContent"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptContentResp) Reset() {
	*x = DecryptContentResp{}
	mi := &file_encryption_encryption_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptContentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptContentResp) ProtoMessage() {}

func (x *DecryptContentResp) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_encryption_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptContentResp.ProtoReflect.Descriptor instead.
func (*DecryptContentResp) Descriptor() ([]byte, []int) {
	return file_encryption_encryption_proto_rawDescGZIP(), []int{11}
}

func (x *DecryptContentResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *DecryptContentResp) GetMsgContent() *MsgContent {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

var File_encryption_encryption_proto protoreflect.FileDescriptor

const file_encryption_encryption_proto_rawDesc = "" +
	"\n" +
	"\x1bencryption/encryption.proto\x12\x11openim.encryption\">\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\aerrCode\x18\x01 \x01(\x05R\aerrCode\x12\x16\n" +
	"\x06errMsg\x18\x02 \x01(\tR\x06errMsg\"\xee\x01\n" +
	"\n" +
	"MsgContent\x12\x16\n" +
	"\x06sendID\x18\x01 \x01(\tR\x06sendID\x12\x16\n" +
	"\x06recvID\x18\x02 \x01(\tR\x06recvID\x12\x18\n" +
	"\agroupID\x18\x03 \x01(\tR\agroupID\x12 \n" +
	"\vsessionType\x18\x04 \x01(\x05R\vsessionType\x12\x18\n" +
	"\amsgFrom\x18\x05 \x01(\x05R\amsgFrom\x12 \n" +
	"\vcontentType\x18\x06 \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\a \x01(\fR\acontent\x12\x1e\n" +
	"\n" +
	"keyVersion\x18\b \x01(\x05R\n" +
	"keyVersion\"\x94\x01\n" +
	"\x11EncryptContentReq\x12=\n" +
	"\n" +
	"msgContent\x18\x01 \x01(\v2\x1d.openim.encryption.MsgContentR\n" +
	"msgContent\x12\x1e\n" +
	"\n" +
	"recvIDList\x18\x02 \x03(\tR\n" +
	"recvIDList\x12 \n" +
	"\voperationID\x18\x03 \x01(\tR\voperationID\"\x9a\x01\n" +
	"\x12EncryptContentResp\x12=\n" +
	"\n" +
	"CommonResp\x18\x01 \x01(\v2\x1d.openim.encryption.CommonRespR\n" +
	"CommonResp\x12E\n" +
	"\x0emsgContentList\x18\x02 \x03(\v2\x1d.openim.encryption.MsgContentR\x0emsgContentList\"]\n" +
	"\x13GetEncryptionKeyReq\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\x12\x1e\n" +
	"\n" +
	"keyVersion\x18\x02 \x01(\x05R\n" +
	"keyVersion\"8\n" +
	"\n" +
	"VersionKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"]\n" +
	"\x14GetEncryptionKeyResp\x12E\n" +
	"\x0eversionKeyList\x18\x02 \x03(\v2\x1d.openim.encryption.VersionKeyR\x0eversionKeyList\"=\n" +
	"\x13GenEncryptionKeyReq\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\"\x16\n" +
	"\x14GenEncryptionKeyResp\"W\n" +
	"\x0fGroupVersionKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\agroupID\x18\x03 \x01(\tR\agroupID\"t\n" +
	"\x11DecryptContentReq\x12=\n" +
	"\n" +
	"msgContent\x18\x01 \x01(\v2\x1d.openim.encryption.MsgContentR\n" +
	"msgContent\x12 \n" +
	"\voperationID\x18\x02 \x01(\tR\voperationID\"\x92\x01\n" +
	"\x12DecryptContentResp\x12=\n" +
	"\n" +
	"CommonResp\x18\x01 \x01(\v2\x1d.openim.encryption.CommonRespR\n" +
	"CommonResp\x12=\n" +
	"\n" +
	"msgContent\x18\x02 \x01(\v2\x1d.openim.encryption.MsgContentR\n" +
	"msgContent2\xd6\x01\n" +
	"\n" +
	"encryption\x12c\n" +
	"\x10GetEncryptionKey\x12&.openim.encryption.GetEncryptionKeyReq\x1a'.openim.encryption.GetEncryptionKeyResp\x12c\n" +
	"\x10GenEncryptionKey\x12&.openim.encryption.GenEncryptionKeyReq\x1a'.openim.encryption.GenEncryptionKeyRespB*Z(github.com/openimsdk/protocol/encryptionb\x06proto3"

var (
	file_encryption_encryption_proto_rawDescOnce sync.Once
	file_encryption_encryption_proto_rawDescData []byte
)

func file_encryption_encryption_proto_rawDescGZIP() []byte {
	file_encryption_encryption_proto_rawDescOnce.Do(func() {
		file_encryption_encryption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encryption_encryption_proto_rawDesc), len(file_encryption_encryption_proto_rawDesc)))
	})
	return file_encryption_encryption_proto_rawDescData
}

var file_encryption_encryption_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_encryption_encryption_proto_goTypes = []any{
	(*CommonResp)(nil),           // 0: openim.encryption.CommonResp
	(*MsgContent)(nil),           // 1: openim.encryption.MsgContent
	(*EncryptContentReq)(nil),    // 2: openim.encryption.EncryptContentReq
	(*EncryptContentResp)(nil),   // 3: openim.encryption.EncryptContentResp
	(*GetEncryptionKeyReq)(nil),  // 4: openim.encryption.GetEncryptionKeyReq
	(*VersionKey)(nil),           // 5: openim.encryption.VersionKey
	(*GetEncryptionKeyResp)(nil), // 6: openim.encryption.GetEncryptionKeyResp
	(*GenEncryptionKeyReq)(nil),  // 7: openim.encryption.GenEncryptionKeyReq
	(*GenEncryptionKeyResp)(nil), // 8: openim.encryption.GenEncryptionKeyResp
	(*GroupVersionKey)(nil),      // 9: openim.encryption.GroupVersionKey
	(*DecryptContentReq)(nil),    // 10: openim.encryption.DecryptContentReq
	(*DecryptContentResp)(nil),   // 11: openim.encryption.DecryptContentResp
}
var file_encryption_encryption_proto_depIdxs = []int32{
	1, // 0: openim.encryption.EncryptContentReq.msgContent:type_name -> openim.encryption.MsgContent
	0, // 1: openim.encryption.EncryptContentResp.CommonResp:type_name -> openim.encryption.CommonResp
	1, // 2: openim.encryption.EncryptContentResp.msgContentList:type_name -> openim.encryption.MsgContent
	5, // 3: openim.encryption.GetEncryptionKeyResp.versionKeyList:type_name -> openim.encryption.VersionKey
	1, // 4: openim.encryption.DecryptContentReq.msgContent:type_name -> openim.encryption.MsgContent
	0, // 5: openim.encryption.DecryptContentResp.CommonResp:type_name -> openim.encryption.CommonResp
	1, // 6: openim.encryption.DecryptContentResp.msgContent:type_name -> openim.encryption.MsgContent
	4, // 7: openim.encryption.encryption.GetEncryptionKey:input_type -> openim.encryption.GetEncryptionKeyReq
	7, // 8: openim.encryption.encryption.GenEncryptionKey:input_type -> openim.encryption.GenEncryptionKeyReq
	6, // 9: openim.encryption.encryption.GetEncryptionKey:output_type -> openim.encryption.GetEncryptionKeyResp
	8, // 10: openim.encryption.encryption.GenEncryptionKey:output_type -> openim.encryption.GenEncryptionKeyResp
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_encryption_encryption_proto_init() }
func file_encryption_encryption_proto_init() {
	if File_encryption_encryption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encryption_encryption_proto_rawDesc), len(file_encryption_encryption_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encryption_encryption_proto_goTypes,
		DependencyIndexes: file_encryption_encryption_proto_depIdxs,
		MessageInfos:      file_encryption_encryption_proto_msgTypes,
	}.Build()
	File_encryption_encryption_proto = out.File
	file_encryption_encryption_proto_goTypes = nil
	file_encryption_encryption_proto_depIdxs = nil
}
