// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.0
// source: extendmsg/extendmsg.proto

package extendmsg

import (
	wrapperspb "github.com/openimsdk/protocol/wrapperspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtendMsgSet struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationID   string                 `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID"`
	SessionType      int32                  `protobuf:"varint,2,opt,name=sessionType,proto3" json:"sessionType"`
	ExtendMsgs       map[string]*ExtendMsg  `protobuf:"bytes,3,rep,name=extendMsgs,proto3" json:"extendMsgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxMsgUpdateTime int64                  `protobuf:"varint,4,opt,name=MaxMsgUpdateTime,proto3" json:"MaxMsgUpdateTime"`
	ExtendMsgNum     int32                  `protobuf:"varint,5,opt,name=extendMsgNum,proto3" json:"extendMsgNum"`
	CreateTime       int64                  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtendMsgSet) Reset() {
	*x = ExtendMsgSet{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendMsgSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendMsgSet) ProtoMessage() {}

func (x *ExtendMsgSet) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendMsgSet.ProtoReflect.Descriptor instead.
func (*ExtendMsgSet) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{0}
}

func (x *ExtendMsgSet) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *ExtendMsgSet) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *ExtendMsgSet) GetExtendMsgs() map[string]*ExtendMsg {
	if x != nil {
		return x.ExtendMsgs
	}
	return nil
}

func (x *ExtendMsgSet) GetMaxMsgUpdateTime() int64 {
	if x != nil {
		return x.MaxMsgUpdateTime
	}
	return 0
}

func (x *ExtendMsgSet) GetExtendMsgNum() int32 {
	if x != nil {
		return x.ExtendMsgNum
	}
	return 0
}

func (x *ExtendMsgSet) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ExtendMsg struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReactionExtensionList map[string]*KeyValue   `protobuf:"bytes,1,rep,name=reactionExtensionList,proto3" json:"reactionExtensionList,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientMsgID           string                 `protobuf:"bytes,2,opt,name=clientMsgID,proto3" json:"clientMsgID"`
	MsgFirstModifyTime    int64                  `protobuf:"varint,3,opt,name=msgFirstModifyTime,proto3" json:"msgFirstModifyTime"`
	AttachedInfo          string                 `protobuf:"bytes,4,opt,name=attachedInfo,proto3" json:"attachedInfo"`
	Ex                    string                 `protobuf:"bytes,5,opt,name=ex,proto3" json:"ex"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExtendMsg) Reset() {
	*x = ExtendMsg{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendMsg) ProtoMessage() {}

func (x *ExtendMsg) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendMsg.ProtoReflect.Descriptor instead.
func (*ExtendMsg) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{1}
}

func (x *ExtendMsg) GetReactionExtensionList() map[string]*KeyValue {
	if x != nil {
		return x.ReactionExtensionList
	}
	return nil
}

func (x *ExtendMsg) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *ExtendMsg) GetMsgFirstModifyTime() int64 {
	if x != nil {
		return x.MsgFirstModifyTime
	}
	return 0
}

func (x *ExtendMsg) GetAttachedInfo() string {
	if x != nil {
		return x.AttachedInfo
	}
	return ""
}

func (x *ExtendMsg) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type KeyValue struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TypeKey          string                 `protobuf:"bytes,1,opt,name=typeKey,proto3" json:"typeKey"`
	Value            string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	LatestUpdateTime int64                  `protobuf:"varint,3,opt,name=latestUpdateTime,proto3" json:"latestUpdateTime"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValue) GetTypeKey() string {
	if x != nil {
		return x.TypeKey
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KeyValue) GetLatestUpdateTime() int64 {
	if x != nil {
		return x.LatestUpdateTime
	}
	return 0
}

type ReactionMessageModifierNotification struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ConversationID            string                 `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID"`
	OpUserID                  string                 `protobuf:"bytes,2,opt,name=opUserID,proto3" json:"opUserID"`
	SessionType               int32                  `protobuf:"varint,3,opt,name=sessionType,proto3" json:"sessionType"`
	SuccessReactionExtensions map[string]*KeyValue   `protobuf:"bytes,4,rep,name=successReactionExtensions,proto3" json:"successReactionExtensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientMsgID               string                 `protobuf:"bytes,5,opt,name=clientMsgID,proto3" json:"clientMsgID"`
	IsReact                   bool                   `protobuf:"varint,6,opt,name=isReact,proto3" json:"isReact"`
	IsExternalExtensions      bool                   `protobuf:"varint,7,opt,name=isExternalExtensions,proto3" json:"isExternalExtensions"`
	MsgFirstModifyTime        int64                  `protobuf:"varint,8,opt,name=msgFirstModifyTime,proto3" json:"msgFirstModifyTime"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ReactionMessageModifierNotification) Reset() {
	*x = ReactionMessageModifierNotification{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionMessageModifierNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionMessageModifierNotification) ProtoMessage() {}

func (x *ReactionMessageModifierNotification) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionMessageModifierNotification.ProtoReflect.Descriptor instead.
func (*ReactionMessageModifierNotification) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{3}
}

func (x *ReactionMessageModifierNotification) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *ReactionMessageModifierNotification) GetOpUserID() string {
	if x != nil {
		return x.OpUserID
	}
	return ""
}

func (x *ReactionMessageModifierNotification) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *ReactionMessageModifierNotification) GetSuccessReactionExtensions() map[string]*KeyValue {
	if x != nil {
		return x.SuccessReactionExtensions
	}
	return nil
}

func (x *ReactionMessageModifierNotification) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *ReactionMessageModifierNotification) GetIsReact() bool {
	if x != nil {
		return x.IsReact
	}
	return false
}

func (x *ReactionMessageModifierNotification) GetIsExternalExtensions() bool {
	if x != nil {
		return x.IsExternalExtensions
	}
	return false
}

func (x *ReactionMessageModifierNotification) GetMsgFirstModifyTime() int64 {
	if x != nil {
		return x.MsgFirstModifyTime
	}
	return 0
}

type ModifyMessageReactionExtensionsReq struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	ConversationID       string                  `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID"`
	SessionType          int32                   `protobuf:"varint,2,opt,name=sessionType,proto3" json:"sessionType"`
	ReactionExtensions   map[string]*KeyValue    `protobuf:"bytes,3,rep,name=reactionExtensions,proto3" json:"reactionExtensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientMsgID          string                  `protobuf:"bytes,4,opt,name=clientMsgID,proto3" json:"clientMsgID"`
	Ex                   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=ex,proto3" json:"ex"`
	AttachedInfo         *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=attachedInfo,proto3" json:"attachedInfo"`
	IsReact              bool                    `protobuf:"varint,7,opt,name=isReact,proto3" json:"isReact"`
	IsExternalExtensions bool                    `protobuf:"varint,8,opt,name=isExternalExtensions,proto3" json:"isExternalExtensions"`
	MsgFirstModifyTime   int64                   `protobuf:"varint,9,opt,name=msgFirstModifyTime,proto3" json:"msgFirstModifyTime"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ModifyMessageReactionExtensionsReq) Reset() {
	*x = ModifyMessageReactionExtensionsReq{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyMessageReactionExtensionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyMessageReactionExtensionsReq) ProtoMessage() {}

func (x *ModifyMessageReactionExtensionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyMessageReactionExtensionsReq.ProtoReflect.Descriptor instead.
func (*ModifyMessageReactionExtensionsReq) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyMessageReactionExtensionsReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *ModifyMessageReactionExtensionsReq) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *ModifyMessageReactionExtensionsReq) GetReactionExtensions() map[string]*KeyValue {
	if x != nil {
		return x.ReactionExtensions
	}
	return nil
}

func (x *ModifyMessageReactionExtensionsReq) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *ModifyMessageReactionExtensionsReq) GetEx() *wrapperspb.StringValue {
	if x != nil {
		return x.Ex
	}
	return nil
}

func (x *ModifyMessageReactionExtensionsReq) GetAttachedInfo() *wrapperspb.StringValue {
	if x != nil {
		return x.AttachedInfo
	}
	return nil
}

func (x *ModifyMessageReactionExtensionsReq) GetIsReact() bool {
	if x != nil {
		return x.IsReact
	}
	return false
}

func (x *ModifyMessageReactionExtensionsReq) GetIsExternalExtensions() bool {
	if x != nil {
		return x.IsExternalExtensions
	}
	return false
}

func (x *ModifyMessageReactionExtensionsReq) GetMsgFirstModifyTime() int64 {
	if x != nil {
		return x.MsgFirstModifyTime
	}
	return 0
}

type SetMessageReactionExtensionsReq struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	ConversationID       string                  `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID"`
	SessionType          int32                   `protobuf:"varint,2,opt,name=sessionType,proto3" json:"sessionType"`
	ReactionExtensions   map[string]*KeyValue    `protobuf:"bytes,3,rep,name=reactionExtensions,proto3" json:"reactionExtensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientMsgID          string                  `protobuf:"bytes,4,opt,name=clientMsgID,proto3" json:"clientMsgID"`
	Ex                   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=ex,proto3" json:"ex"`
	AttachedInfo         *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=attachedInfo,proto3" json:"attachedInfo"`
	IsReact              bool                    `protobuf:"varint,7,opt,name=isReact,proto3" json:"isReact"`
	IsExternalExtensions bool                    `protobuf:"varint,8,opt,name=isExternalExtensions,proto3" json:"isExternalExtensions"`
	MsgFirstModifyTime   int64                   `protobuf:"varint,9,opt,name=msgFirstModifyTime,proto3" json:"msgFirstModifyTime"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SetMessageReactionExtensionsReq) Reset() {
	*x = SetMessageReactionExtensionsReq{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMessageReactionExtensionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageReactionExtensionsReq) ProtoMessage() {}

func (x *SetMessageReactionExtensionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageReactionExtensionsReq.ProtoReflect.Descriptor instead.
func (*SetMessageReactionExtensionsReq) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{5}
}

func (x *SetMessageReactionExtensionsReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *SetMessageReactionExtensionsReq) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *SetMessageReactionExtensionsReq) GetReactionExtensions() map[string]*KeyValue {
	if x != nil {
		return x.ReactionExtensions
	}
	return nil
}

func (x *SetMessageReactionExtensionsReq) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *SetMessageReactionExtensionsReq) GetEx() *wrapperspb.StringValue {
	if x != nil {
		return x.Ex
	}
	return nil
}

func (x *SetMessageReactionExtensionsReq) GetAttachedInfo() *wrapperspb.StringValue {
	if x != nil {
		return x.AttachedInfo
	}
	return nil
}

func (x *SetMessageReactionExtensionsReq) GetIsReact() bool {
	if x != nil {
		return x.IsReact
	}
	return false
}

func (x *SetMessageReactionExtensionsReq) GetIsExternalExtensions() bool {
	if x != nil {
		return x.IsExternalExtensions
	}
	return false
}

func (x *SetMessageReactionExtensionsReq) GetMsgFirstModifyTime() int64 {
	if x != nil {
		return x.MsgFirstModifyTime
	}
	return 0
}

type SetMessageReactionExtensionsResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgID        string                 `protobuf:"bytes,1,opt,name=clientMsgID,proto3" json:"clientMsgID"`
	MsgFirstModifyTime int64                  `protobuf:"varint,2,opt,name=msgFirstModifyTime,proto3" json:"msgFirstModifyTime"`
	IsReact            bool                   `protobuf:"varint,3,opt,name=isReact,proto3" json:"isReact"`
	Result             []*KeyValueResp        `protobuf:"bytes,4,rep,name=result,proto3" json:"result"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetMessageReactionExtensionsResp) Reset() {
	*x = SetMessageReactionExtensionsResp{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMessageReactionExtensionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageReactionExtensionsResp) ProtoMessage() {}

func (x *SetMessageReactionExtensionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageReactionExtensionsResp.ProtoReflect.Descriptor instead.
func (*SetMessageReactionExtensionsResp) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{6}
}

func (x *SetMessageReactionExtensionsResp) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *SetMessageReactionExtensionsResp) GetMsgFirstModifyTime() int64 {
	if x != nil {
		return x.MsgFirstModifyTime
	}
	return 0
}

func (x *SetMessageReactionExtensionsResp) GetIsReact() bool {
	if x != nil {
		return x.IsReact
	}
	return false
}

func (x *SetMessageReactionExtensionsResp) GetResult() []*KeyValueResp {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetMessagesReactionExtensionsReq struct {
	state               protoimpl.MessageState                                 `protogen:"open.v1"`
	ConversationID      string                                                 `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID"`
	SessionType         int32                                                  `protobuf:"varint,2,opt,name=sessionType,proto3" json:"sessionType"`
	MessageReactionKeys []*GetMessagesReactionExtensionsReq_MessageReactionKey `protobuf:"bytes,3,rep,name=messageReactionKeys,proto3" json:"messageReactionKeys"`
	TypeKeys            []string                                               `protobuf:"bytes,4,rep,name=TypeKeys,proto3" json:"TypeKeys"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMessagesReactionExtensionsReq) Reset() {
	*x = GetMessagesReactionExtensionsReq{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesReactionExtensionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesReactionExtensionsReq) ProtoMessage() {}

func (x *GetMessagesReactionExtensionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesReactionExtensionsReq.ProtoReflect.Descriptor instead.
func (*GetMessagesReactionExtensionsReq) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessagesReactionExtensionsReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *GetMessagesReactionExtensionsReq) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *GetMessagesReactionExtensionsReq) GetMessageReactionKeys() []*GetMessagesReactionExtensionsReq_MessageReactionKey {
	if x != nil {
		return x.MessageReactionKeys
	}
	return nil
}

func (x *GetMessagesReactionExtensionsReq) GetTypeKeys() []string {
	if x != nil {
		return x.TypeKeys
	}
	return nil
}

type GetMessagesReactionExtensionsResp struct {
	state               protoimpl.MessageState          `protogen:"open.v1"`
	SingleMessageResult []*SingleMessageExtensionResult `protobuf:"bytes,1,rep,name=singleMessageResult,proto3" json:"singleMessageResult"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMessagesReactionExtensionsResp) Reset() {
	*x = GetMessagesReactionExtensionsResp{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesReactionExtensionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesReactionExtensionsResp) ProtoMessage() {}

func (x *GetMessagesReactionExtensionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesReactionExtensionsResp.ProtoReflect.Descriptor instead.
func (*GetMessagesReactionExtensionsResp) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessagesReactionExtensionsResp) GetSingleMessageResult() []*SingleMessageExtensionResult {
	if x != nil {
		return x.SingleMessageResult
	}
	return nil
}

type SingleMessageExtensionResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ReactionExtensions map[string]*KeyValue   `protobuf:"bytes,1,rep,name=reactionExtensions,proto3" json:"reactionExtensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientMsgID        string                 `protobuf:"bytes,2,opt,name=clientMsgID,proto3" json:"clientMsgID"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SingleMessageExtensionResult) Reset() {
	*x = SingleMessageExtensionResult{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMessageExtensionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMessageExtensionResult) ProtoMessage() {}

func (x *SingleMessageExtensionResult) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMessageExtensionResult.ProtoReflect.Descriptor instead.
func (*SingleMessageExtensionResult) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{9}
}

func (x *SingleMessageExtensionResult) GetReactionExtensions() map[string]*KeyValue {
	if x != nil {
		return x.ReactionExtensions
	}
	return nil
}

func (x *SingleMessageExtensionResult) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

type ModifyMessageReactionExtensionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessList   []*ExtendMsgResp       `protobuf:"bytes,1,rep,name=successList,proto3" json:"successList"`
	FailedList    []*ExtendMsgResp       `protobuf:"bytes,2,rep,name=failedList,proto3" json:"failedList"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyMessageReactionExtensionsResp) Reset() {
	*x = ModifyMessageReactionExtensionsResp{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyMessageReactionExtensionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyMessageReactionExtensionsResp) ProtoMessage() {}

func (x *ModifyMessageReactionExtensionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyMessageReactionExtensionsResp.ProtoReflect.Descriptor instead.
func (*ModifyMessageReactionExtensionsResp) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{10}
}

func (x *ModifyMessageReactionExtensionsResp) GetSuccessList() []*ExtendMsgResp {
	if x != nil {
		return x.SuccessList
	}
	return nil
}

func (x *ModifyMessageReactionExtensionsResp) GetFailedList() []*ExtendMsgResp {
	if x != nil {
		return x.FailedList
	}
	return nil
}

type DeleteMessagesReactionExtensionsReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OperationID          string                 `protobuf:"bytes,1,opt,name=operationID,proto3" json:"operationID"`
	OpUserID             string                 `protobuf:"bytes,2,opt,name=opUserID,proto3" json:"opUserID"`
	ConversationID       string                 `protobuf:"bytes,3,opt,name=conversationID,proto3" json:"conversationID"`
	SessionType          int32                  `protobuf:"varint,4,opt,name=sessionType,proto3" json:"sessionType"`
	ClientMsgID          string                 `protobuf:"bytes,5,opt,name=clientMsgID,proto3" json:"clientMsgID"`
	IsExternalExtensions bool                   `protobuf:"varint,6,opt,name=isExternalExtensions,proto3" json:"isExternalExtensions"`
	MsgFirstModifyTime   int64                  `protobuf:"varint,7,opt,name=msgFirstModifyTime,proto3" json:"msgFirstModifyTime"`
	ReactionExtensions   []*KeyValue            `protobuf:"bytes,8,rep,name=reactionExtensions,proto3" json:"reactionExtensions"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteMessagesReactionExtensionsReq) Reset() {
	*x = DeleteMessagesReactionExtensionsReq{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessagesReactionExtensionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessagesReactionExtensionsReq) ProtoMessage() {}

func (x *DeleteMessagesReactionExtensionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessagesReactionExtensionsReq.ProtoReflect.Descriptor instead.
func (*DeleteMessagesReactionExtensionsReq) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMessagesReactionExtensionsReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *DeleteMessagesReactionExtensionsReq) GetOpUserID() string {
	if x != nil {
		return x.OpUserID
	}
	return ""
}

func (x *DeleteMessagesReactionExtensionsReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *DeleteMessagesReactionExtensionsReq) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *DeleteMessagesReactionExtensionsReq) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *DeleteMessagesReactionExtensionsReq) GetIsExternalExtensions() bool {
	if x != nil {
		return x.IsExternalExtensions
	}
	return false
}

func (x *DeleteMessagesReactionExtensionsReq) GetMsgFirstModifyTime() int64 {
	if x != nil {
		return x.MsgFirstModifyTime
	}
	return 0
}

func (x *DeleteMessagesReactionExtensionsReq) GetReactionExtensions() []*KeyValue {
	if x != nil {
		return x.ReactionExtensions
	}
	return nil
}

type DeleteMessagesReactionExtensionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*KeyValueResp        `protobuf:"bytes,1,rep,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessagesReactionExtensionsResp) Reset() {
	*x = DeleteMessagesReactionExtensionsResp{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessagesReactionExtensionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessagesReactionExtensionsResp) ProtoMessage() {}

func (x *DeleteMessagesReactionExtensionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessagesReactionExtensionsResp.ProtoReflect.Descriptor instead.
func (*DeleteMessagesReactionExtensionsResp) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMessagesReactionExtensionsResp) GetResult() []*KeyValueResp {
	if x != nil {
		return x.Result
	}
	return nil
}

type ExtendMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtendMsg     *ExtendMsg             `protobuf:"bytes,1,opt,name=extendMsg,proto3" json:"extendMsg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendMsgResp) Reset() {
	*x = ExtendMsgResp{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendMsgResp) ProtoMessage() {}

func (x *ExtendMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendMsgResp.ProtoReflect.Descriptor instead.
func (*ExtendMsgResp) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{13}
}

func (x *ExtendMsgResp) GetExtendMsg() *ExtendMsg {
	if x != nil {
		return x.ExtendMsg
	}
	return nil
}

type KeyValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyValue      *KeyValue              `protobuf:"bytes,1,opt,name=keyValue,proto3" json:"keyValue"`
	ErrCode       int32                  `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode"`
	ErrMsg        string                 `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueResp) Reset() {
	*x = KeyValueResp{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueResp) ProtoMessage() {}

func (x *KeyValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueResp.ProtoReflect.Descriptor instead.
func (*KeyValueResp) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{14}
}

func (x *KeyValueResp) GetKeyValue() *KeyValue {
	if x != nil {
		return x.KeyValue
	}
	return nil
}

func (x *KeyValueResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *KeyValueResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type GetMessagesReactionExtensionsReq_MessageReactionKey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgID        string                 `protobuf:"bytes,1,opt,name=clientMsgID,proto3" json:"clientMsgID"`
	MsgFirstModifyTime int64                  `protobuf:"varint,2,opt,name=msgFirstModifyTime,proto3" json:"msgFirstModifyTime"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMessagesReactionExtensionsReq_MessageReactionKey) Reset() {
	*x = GetMessagesReactionExtensionsReq_MessageReactionKey{}
	mi := &file_extendmsg_extendmsg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesReactionExtensionsReq_MessageReactionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesReactionExtensionsReq_MessageReactionKey) ProtoMessage() {}

func (x *GetMessagesReactionExtensionsReq_MessageReactionKey) ProtoReflect() protoreflect.Message {
	mi := &file_extendmsg_extendmsg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesReactionExtensionsReq_MessageReactionKey.ProtoReflect.Descriptor instead.
func (*GetMessagesReactionExtensionsReq_MessageReactionKey) Descriptor() ([]byte, []int) {
	return file_extendmsg_extendmsg_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetMessagesReactionExtensionsReq_MessageReactionKey) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *GetMessagesReactionExtensionsReq_MessageReactionKey) GetMsgFirstModifyTime() int64 {
	if x != nil {
		return x.MsgFirstModifyTime
	}
	return 0
}

var File_extendmsg_extendmsg_proto protoreflect.FileDescriptor

const file_extendmsg_extendmsg_proto_rawDesc = "" +
	"\n" +
	"\x19extendmsg/extendmsg.proto\x12\x10openim.extendMsg\x1a\x1bwrapperspb/wrapperspb.proto\"\xf4\x02\n" +
	"\fExtendMsgSet\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\x12 \n" +
	"\vsessionType\x18\x02 \x01(\x05R\vsessionType\x12N\n" +
	"\n" +
	"extendMsgs\x18\x03 \x03(\v2..openim.extendMsg.ExtendMsgSet.ExtendMsgsEntryR\n" +
	"extendMsgs\x12*\n" +
	"\x10MaxMsgUpdateTime\x18\x04 \x01(\x03R\x10MaxMsgUpdateTime\x12\"\n" +
	"\fextendMsgNum\x18\x05 \x01(\x05R\fextendMsgNum\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\x03R\n" +
	"createTime\x1aZ\n" +
	"\x0fExtendMsgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.openim.extendMsg.ExtendMsgR\x05value:\x028\x01\"\xe5\x02\n" +
	"\tExtendMsg\x12l\n" +
	"\x15reactionExtensionList\x18\x01 \x03(\v26.openim.extendMsg.ExtendMsg.ReactionExtensionListEntryR\x15reactionExtensionList\x12 \n" +
	"\vclientMsgID\x18\x02 \x01(\tR\vclientMsgID\x12.\n" +
	"\x12msgFirstModifyTime\x18\x03 \x01(\x03R\x12msgFirstModifyTime\x12\"\n" +
	"\fattachedInfo\x18\x04 \x01(\tR\fattachedInfo\x12\x0e\n" +
	"\x02ex\x18\x05 \x01(\tR\x02ex\x1ad\n" +
	"\x1aReactionExtensionListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.openim.extendMsg.KeyValueR\x05value:\x028\x01\"f\n" +
	"\bKeyValue\x12\x18\n" +
	"\atypeKey\x18\x01 \x01(\tR\atypeKey\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12*\n" +
	"\x10latestUpdateTime\x18\x03 \x01(\x03R\x10latestUpdateTime\"\xaa\x04\n" +
	"#ReactionMessageModifierNotification\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\x12\x1a\n" +
	"\bopUserID\x18\x02 \x01(\tR\bopUserID\x12 \n" +
	"\vsessionType\x18\x03 \x01(\x05R\vsessionType\x12\x92\x01\n" +
	"\x19successReactionExtensions\x18\x04 \x03(\v2T.openim.extendMsg.ReactionMessageModifierNotification.SuccessReactionExtensionsEntryR\x19successReactionExtensions\x12 \n" +
	"\vclientMsgID\x18\x05 \x01(\tR\vclientMsgID\x12\x18\n" +
	"\aisReact\x18\x06 \x01(\bR\aisReact\x122\n" +
	"\x14isExternalExtensions\x18\a \x01(\bR\x14isExternalExtensions\x12.\n" +
	"\x12msgFirstModifyTime\x18\b \x01(\x03R\x12msgFirstModifyTime\x1ah\n" +
	"\x1eSuccessReactionExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.openim.extendMsg.KeyValueR\x05value:\x028\x01\"\xdf\x04\n" +
	"\"ModifyMessageReactionExtensionsReq\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\x12 \n" +
	"\vsessionType\x18\x02 \x01(\x05R\vsessionType\x12|\n" +
	"\x12reactionExtensions\x18\x03 \x03(\v2L.openim.extendMsg.ModifyMessageReactionExtensionsReq.ReactionExtensionsEntryR\x12reactionExtensions\x12 \n" +
	"\vclientMsgID\x18\x04 \x01(\tR\vclientMsgID\x12,\n" +
	"\x02ex\x18\x05 \x01(\v2\x1c.openim.protobuf.StringValueR\x02ex\x12@\n" +
	"\fattachedInfo\x18\x06 \x01(\v2\x1c.openim.protobuf.StringValueR\fattachedInfo\x12\x18\n" +
	"\aisReact\x18\a \x01(\bR\aisReact\x122\n" +
	"\x14isExternalExtensions\x18\b \x01(\bR\x14isExternalExtensions\x12.\n" +
	"\x12msgFirstModifyTime\x18\t \x01(\x03R\x12msgFirstModifyTime\x1aa\n" +
	"\x17ReactionExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.openim.extendMsg.KeyValueR\x05value:\x028\x01\"\xd9\x04\n" +
	"\x1fSetMessageReactionExtensionsReq\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\x12 \n" +
	"\vsessionType\x18\x02 \x01(\x05R\vsessionType\x12y\n" +
	"\x12reactionExtensions\x18\x03 \x03(\v2I.openim.extendMsg.SetMessageReactionExtensionsReq.ReactionExtensionsEntryR\x12reactionExtensions\x12 \n" +
	"\vclientMsgID\x18\x04 \x01(\tR\vclientMsgID\x12,\n" +
	"\x02ex\x18\x05 \x01(\v2\x1c.openim.protobuf.StringValueR\x02ex\x12@\n" +
	"\fattachedInfo\x18\x06 \x01(\v2\x1c.openim.protobuf.StringValueR\fattachedInfo\x12\x18\n" +
	"\aisReact\x18\a \x01(\bR\aisReact\x122\n" +
	"\x14isExternalExtensions\x18\b \x01(\bR\x14isExternalExtensions\x12.\n" +
	"\x12msgFirstModifyTime\x18\t \x01(\x03R\x12msgFirstModifyTime\x1aa\n" +
	"\x17ReactionExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.openim.extendMsg.KeyValueR\x05value:\x028\x01\"\xc6\x01\n" +
	" SetMessageReactionExtensionsResp\x12 \n" +
	"\vclientMsgID\x18\x01 \x01(\tR\vclientMsgID\x12.\n" +
	"\x12msgFirstModifyTime\x18\x02 \x01(\x03R\x12msgFirstModifyTime\x12\x18\n" +
	"\aisReact\x18\x03 \x01(\bR\aisReact\x126\n" +
	"\x06result\x18\x04 \x03(\v2\x1e.openim.extendMsg.KeyValueRespR\x06result\"\xe9\x02\n" +
	" GetMessagesReactionExtensionsReq\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\x12 \n" +
	"\vsessionType\x18\x02 \x01(\x05R\vsessionType\x12w\n" +
	"\x13messageReactionKeys\x18\x03 \x03(\v2E.openim.extendMsg.GetMessagesReactionExtensionsReq.MessageReactionKeyR\x13messageReactionKeys\x12\x1a\n" +
	"\bTypeKeys\x18\x04 \x03(\tR\bTypeKeys\x1af\n" +
	"\x12MessageReactionKey\x12 \n" +
	"\vclientMsgID\x18\x01 \x01(\tR\vclientMsgID\x12.\n" +
	"\x12msgFirstModifyTime\x18\x02 \x01(\x03R\x12msgFirstModifyTime\"\x85\x01\n" +
	"!GetMessagesReactionExtensionsResp\x12`\n" +
	"\x13singleMessageResult\x18\x01 \x03(\v2..openim.extendMsg.SingleMessageExtensionResultR\x13singleMessageResult\"\x9b\x02\n" +
	"\x1cSingleMessageExtensionResult\x12v\n" +
	"\x12reactionExtensions\x18\x01 \x03(\v2F.openim.extendMsg.SingleMessageExtensionResult.ReactionExtensionsEntryR\x12reactionExtensions\x12 \n" +
	"\vclientMsgID\x18\x02 \x01(\tR\vclientMsgID\x1aa\n" +
	"\x17ReactionExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.openim.extendMsg.KeyValueR\x05value:\x028\x01\"\xa9\x01\n" +
	"#ModifyMessageReactionExtensionsResp\x12A\n" +
	"\vsuccessList\x18\x01 \x03(\v2\x1f.openim.extendMsg.ExtendMsgRespR\vsuccessList\x12?\n" +
	"\n" +
	"failedList\x18\x02 \x03(\v2\x1f.openim.extendMsg.ExtendMsgRespR\n" +
	"failedList\"\xff\x02\n" +
	"#DeleteMessagesReactionExtensionsReq\x12 \n" +
	"\voperationID\x18\x01 \x01(\tR\voperationID\x12\x1a\n" +
	"\bopUserID\x18\x02 \x01(\tR\bopUserID\x12&\n" +
	"\x0econversationID\x18\x03 \x01(\tR\x0econversationID\x12 \n" +
	"\vsessionType\x18\x04 \x01(\x05R\vsessionType\x12 \n" +
	"\vclientMsgID\x18\x05 \x01(\tR\vclientMsgID\x122\n" +
	"\x14isExternalExtensions\x18\x06 \x01(\bR\x14isExternalExtensions\x12.\n" +
	"\x12msgFirstModifyTime\x18\a \x01(\x03R\x12msgFirstModifyTime\x12J\n" +
	"\x12reactionExtensions\x18\b \x03(\v2\x1a.openim.extendMsg.KeyValueR\x12reactionExtensions\"^\n" +
	"$DeleteMessagesReactionExtensionsResp\x126\n" +
	"\x06result\x18\x01 \x03(\v2\x1e.openim.extendMsg.KeyValueRespR\x06result\"J\n" +
	"\rExtendMsgResp\x129\n" +
	"\textendMsg\x18\x01 \x01(\v2\x1b.openim.extendMsg.ExtendMsgR\textendMsg\"x\n" +
	"\fKeyValueResp\x126\n" +
	"\bkeyValue\x18\x01 \x01(\v2\x1a.openim.extendMsg.KeyValueR\bkeyValue\x12\x18\n" +
	"\aerrCode\x18\x02 \x01(\x05R\aerrCode\x12\x16\n" +
	"\x06errMsg\x18\x03 \x01(\tR\x06errMsgB)Z'github.com/openimsdk/protocol/extendmsgb\x06proto3"

var (
	file_extendmsg_extendmsg_proto_rawDescOnce sync.Once
	file_extendmsg_extendmsg_proto_rawDescData []byte
)

func file_extendmsg_extendmsg_proto_rawDescGZIP() []byte {
	file_extendmsg_extendmsg_proto_rawDescOnce.Do(func() {
		file_extendmsg_extendmsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extendmsg_extendmsg_proto_rawDesc), len(file_extendmsg_extendmsg_proto_rawDesc)))
	})
	return file_extendmsg_extendmsg_proto_rawDescData
}

var file_extendmsg_extendmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_extendmsg_extendmsg_proto_goTypes = []any{
	(*ExtendMsgSet)(nil),                         // 0: openim.extendMsg.ExtendMsgSet
	(*ExtendMsg)(nil),                            // 1: openim.extendMsg.ExtendMsg
	(*KeyValue)(nil),                             // 2: openim.extendMsg.KeyValue
	(*ReactionMessageModifierNotification)(nil),  // 3: openim.extendMsg.ReactionMessageModifierNotification
	(*ModifyMessageReactionExtensionsReq)(nil),   // 4: openim.extendMsg.ModifyMessageReactionExtensionsReq
	(*SetMessageReactionExtensionsReq)(nil),      // 5: openim.extendMsg.SetMessageReactionExtensionsReq
	(*SetMessageReactionExtensionsResp)(nil),     // 6: openim.extendMsg.SetMessageReactionExtensionsResp
	(*GetMessagesReactionExtensionsReq)(nil),     // 7: openim.extendMsg.GetMessagesReactionExtensionsReq
	(*GetMessagesReactionExtensionsResp)(nil),    // 8: openim.extendMsg.GetMessagesReactionExtensionsResp
	(*SingleMessageExtensionResult)(nil),         // 9: openim.extendMsg.SingleMessageExtensionResult
	(*ModifyMessageReactionExtensionsResp)(nil),  // 10: openim.extendMsg.ModifyMessageReactionExtensionsResp
	(*DeleteMessagesReactionExtensionsReq)(nil),  // 11: openim.extendMsg.DeleteMessagesReactionExtensionsReq
	(*DeleteMessagesReactionExtensionsResp)(nil), // 12: openim.extendMsg.DeleteMessagesReactionExtensionsResp
	(*ExtendMsgResp)(nil),                        // 13: openim.extendMsg.ExtendMsgResp
	(*KeyValueResp)(nil),                         // 14: openim.extendMsg.KeyValueResp
	nil,                                          // 15: openim.extendMsg.ExtendMsgSet.ExtendMsgsEntry
	nil,                                          // 16: openim.extendMsg.ExtendMsg.ReactionExtensionListEntry
	nil,                                          // 17: openim.extendMsg.ReactionMessageModifierNotification.SuccessReactionExtensionsEntry
	nil,                                          // 18: openim.extendMsg.ModifyMessageReactionExtensionsReq.ReactionExtensionsEntry
	nil,                                          // 19: openim.extendMsg.SetMessageReactionExtensionsReq.ReactionExtensionsEntry
	(*GetMessagesReactionExtensionsReq_MessageReactionKey)(nil), // 20: openim.extendMsg.GetMessagesReactionExtensionsReq.MessageReactionKey
	nil,                            // 21: openim.extendMsg.SingleMessageExtensionResult.ReactionExtensionsEntry
	(*wrapperspb.StringValue)(nil), // 22: openim.protobuf.StringValue
}
var file_extendmsg_extendmsg_proto_depIdxs = []int32{
	15, // 0: openim.extendMsg.ExtendMsgSet.extendMsgs:type_name -> openim.extendMsg.ExtendMsgSet.ExtendMsgsEntry
	16, // 1: openim.extendMsg.ExtendMsg.reactionExtensionList:type_name -> openim.extendMsg.ExtendMsg.ReactionExtensionListEntry
	17, // 2: openim.extendMsg.ReactionMessageModifierNotification.successReactionExtensions:type_name -> openim.extendMsg.ReactionMessageModifierNotification.SuccessReactionExtensionsEntry
	18, // 3: openim.extendMsg.ModifyMessageReactionExtensionsReq.reactionExtensions:type_name -> openim.extendMsg.ModifyMessageReactionExtensionsReq.ReactionExtensionsEntry
	22, // 4: openim.extendMsg.ModifyMessageReactionExtensionsReq.ex:type_name -> openim.protobuf.StringValue
	22, // 5: openim.extendMsg.ModifyMessageReactionExtensionsReq.attachedInfo:type_name -> openim.protobuf.StringValue
	19, // 6: openim.extendMsg.SetMessageReactionExtensionsReq.reactionExtensions:type_name -> openim.extendMsg.SetMessageReactionExtensionsReq.ReactionExtensionsEntry
	22, // 7: openim.extendMsg.SetMessageReactionExtensionsReq.ex:type_name -> openim.protobuf.StringValue
	22, // 8: openim.extendMsg.SetMessageReactionExtensionsReq.attachedInfo:type_name -> openim.protobuf.StringValue
	14, // 9: openim.extendMsg.SetMessageReactionExtensionsResp.result:type_name -> openim.extendMsg.KeyValueResp
	20, // 10: openim.extendMsg.GetMessagesReactionExtensionsReq.messageReactionKeys:type_name -> openim.extendMsg.GetMessagesReactionExtensionsReq.MessageReactionKey
	9,  // 11: openim.extendMsg.GetMessagesReactionExtensionsResp.singleMessageResult:type_name -> openim.extendMsg.SingleMessageExtensionResult
	21, // 12: openim.extendMsg.SingleMessageExtensionResult.reactionExtensions:type_name -> openim.extendMsg.SingleMessageExtensionResult.ReactionExtensionsEntry
	13, // 13: openim.extendMsg.ModifyMessageReactionExtensionsResp.successList:type_name -> openim.extendMsg.ExtendMsgResp
	13, // 14: openim.extendMsg.ModifyMessageReactionExtensionsResp.failedList:type_name -> openim.extendMsg.ExtendMsgResp
	2,  // 15: openim.extendMsg.DeleteMessagesReactionExtensionsReq.reactionExtensions:type_name -> openim.extendMsg.KeyValue
	14, // 16: openim.extendMsg.DeleteMessagesReactionExtensionsResp.result:type_name -> openim.extendMsg.KeyValueResp
	1,  // 17: openim.extendMsg.ExtendMsgResp.extendMsg:type_name -> openim.extendMsg.ExtendMsg
	2,  // 18: openim.extendMsg.KeyValueResp.keyValue:type_name -> openim.extendMsg.KeyValue
	1,  // 19: openim.extendMsg.ExtendMsgSet.ExtendMsgsEntry.value:type_name -> openim.extendMsg.ExtendMsg
	2,  // 20: openim.extendMsg.ExtendMsg.ReactionExtensionListEntry.value:type_name -> openim.extendMsg.KeyValue
	2,  // 21: openim.extendMsg.ReactionMessageModifierNotification.SuccessReactionExtensionsEntry.value:type_name -> openim.extendMsg.KeyValue
	2,  // 22: openim.extendMsg.ModifyMessageReactionExtensionsReq.ReactionExtensionsEntry.value:type_name -> openim.extendMsg.KeyValue
	2,  // 23: openim.extendMsg.SetMessageReactionExtensionsReq.ReactionExtensionsEntry.value:type_name -> openim.extendMsg.KeyValue
	2,  // 24: openim.extendMsg.SingleMessageExtensionResult.ReactionExtensionsEntry.value:type_name -> openim.extendMsg.KeyValue
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_extendmsg_extendmsg_proto_init() }
func file_extendmsg_extendmsg_proto_init() {
	if File_extendmsg_extendmsg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extendmsg_extendmsg_proto_rawDesc), len(file_extendmsg_extendmsg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extendmsg_extendmsg_proto_goTypes,
		DependencyIndexes: file_extendmsg_extendmsg_proto_depIdxs,
		MessageInfos:      file_extendmsg_extendmsg_proto_msgTypes,
	}.Build()
	File_extendmsg_extendmsg_proto = out.File
	file_extendmsg_extendmsg_proto_goTypes = nil
	file_extendmsg_extendmsg_proto_depIdxs = nil
}
