packages:
  - .
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - electron
  - es5-ext
  - esbuild
  - koffi

patchedDependencies:
  '@openim/wasm-client-sdk@3.8.5': patches/@openim__wasm-client-sdk@3.8.5.patch
