import type { ReactNode, MouseEventHandler } from 'react';

// ============================================================================
// Attachment Types
// ============================================================================

/**
 * Represents a file attachment in plain mode
 */
export interface Attachment {
  /** Unique identifier generated by the component */
  id: string;
  /** Original File object */
  file: File;
  /** File name */
  name: string;
  /** File size in bytes */
  size: number;
  /** MIME type */
  mime: string;
  /** File last modified timestamp */
  lastModified?: number;
  /** Preview URL for images (objectURL) */
  previewUrl?: string;
}

// ============================================================================
// Mention Types
// ============================================================================

/**
 * Information about a mention in the message
 */
export interface MentionInfo {
  /** User ID */
  userId: string;
  /** Display name */
  display: string;
  /** Start index in plainText (UTF-16, inclusive) */
  start: number;
  /** End index in plainText (UTF-16, exclusive) */
  end: number;
}

/**
 * Member data for mention suggestions
 */
export interface Member {
  /** Unique user identifier */
  userId: string;
  /** Display name shown in the editor */
  display: string;
  /** Optional avatar URL */
  avatarUrl?: string;
}

// ============================================================================
// Quote Types
// ============================================================================

/**
 * Quoted message information
 */
export interface QuoteInfo {
  /** Quote title, e.g., "Reply to Alice:" */
  title: string;
  /** Quoted content */
  content: string;
}

// ============================================================================
// Payload Types
// ============================================================================

/**
 * Result from image upload handler
 */
export interface UploadImageResult {
  /** URL of the uploaded image */
  url: string;
  /** Optional alt text */
  alt?: string;
}

/**
 * Progress callback for image upload
 */
export interface UploadProgressEvent {
  /** Upload progress percentage (0-100) */
  progress: number;
}

/**
 * Image upload function type with optional progress callback
 */
export type UploadImageFn = (
  file: File,
  onProgress?: (event: UploadProgressEvent) => void
) => Promise<UploadImageResult>;

/**
 * Payload for plain text mode messages
 */
export interface PlainMessagePayload {
  type: 'text';
  /** Plain text with mentions as @userId */
  plainText: string;
  /** List of mentions with their positions */
  mentions: MentionInfo[];
  /** List of attached files */
  attachments: Attachment[];
  /** Quoted message (if any) */
  quote?: QuoteInfo;
}

/**
 * Payload for rich text mode messages (Markdown)
 */
export interface MarkdownMessagePayload {
  type: 'markdown';
  /** Markdown content */
  markdown: string;
}

/**
 * Union type for all message payloads
 */
export type MessagePayload = PlainMessagePayload | MarkdownMessagePayload;

// ============================================================================
// Draft Types
// ============================================================================

/**
 * Draft state for saving/restoring editor content
 */
export interface ComposerDraft {
  /** Editor mode */
  mode?: EditorMode;
  /** Serialized editor state (JSON string from getJSON) - deprecated, use json */
  editorState?: string;
  /** Editor JSON content */
  json?: Record<string, unknown>;
  /** Attachments (plain mode only) */
  attachments?: Attachment[];
  /** Quick restore text for plain mode */
  text?: string;
  /** Quote information (plain mode only) */
  quote?: QuoteInfo;
}

// ============================================================================
// Locale Types
// ============================================================================

/**
 * Locale strings for internationalization
 */
export interface IMComposerLocale {
  /** Placeholder text for plain mode */
  placeholderPlain?: string;
  /** Placeholder text for rich mode */
  placeholderRich?: string;
  /** No results found in mention list */
  mentionNoResults?: string;
  /** Loading text for mention list */
  mentionLoading?: string;
  /** Error text for mention list */
  mentionError?: string;
  /** Remove attachment button label */
  removeAttachment?: string;
  /** Remove quote button label */
  removeQuote?: string;
  /** Upload failed message */
  uploadFailed?: string;
  /** Uploading text */
  uploading?: string;

  // Toolbar buttons
  /** Undo button */
  undo?: string;
  /** Redo button */
  redo?: string;
  /** Heading dropdown */
  heading?: string;
  /** Heading 1 */
  heading1?: string;
  /** Heading 2 */
  heading2?: string;
  /** Heading 3 */
  heading3?: string;
  /** Heading 4 */
  heading4?: string;
  /** Paragraph */
  paragraph?: string;
  /** List dropdown */
  list?: string;
  /** Bullet list */
  bulletList?: string;
  /** Ordered list */
  orderedList?: string;
  /** Task list */
  taskList?: string;
  /** Blockquote button */
  blockquote?: string;
  /** Code block button */
  codeBlock?: string;
  /** Bold button */
  bold?: string;
  /** Italic button */
  italic?: string;
  /** Strikethrough button */
  strike?: string;
  /** Inline code button */
  code?: string;
  /** Underline button */
  underline?: string;
  /** Highlight button */
  highlight?: string;
  /** Remove highlight */
  removeHighlight?: string;
  /** Link button */
  link?: string;
  /** Link input placeholder */
  linkPlaceholder?: string;
  /** Apply link */
  applyLink?: string;
  /** Open link */
  openLink?: string;
  /** Remove link */
  removeLink?: string;
  /** Superscript button */
  superscript?: string;
  /** Subscript button */
  subscript?: string;
  /** Align left button */
  alignLeft?: string;
  /** Align center button */
  alignCenter?: string;
  /** Align right button */
  alignRight?: string;
  /** Align justify button */
  alignJustify?: string;
  /** Insert image button */
  insertImage?: string;
  /** Upload image */
  uploadImage?: string;
  /** Click to upload */
  clickToUpload?: string;
  /** Or drag and drop */
  orDragAndDrop?: string;
  /** Maximum files */
  maxFiles?: string;
  /** Clear all */
  clearAll?: string;
}

/**
 * Default English locale
 */
export const defaultLocale: IMComposerLocale = {
  placeholderPlain: 'Type a message...',
  placeholderRich: 'Write something...',
  mentionNoResults: 'No results found',
  mentionLoading: 'Loading...',
  mentionError: 'Failed to load',
  removeAttachment: 'Remove',
  removeQuote: 'Remove quote',
  uploadFailed: 'Upload failed',
  uploading: 'Uploading...',

  // Toolbar buttons
  undo: 'Undo',
  redo: 'Redo',
  heading: 'Heading',
  heading1: 'Heading 1',
  heading2: 'Heading 2',
  heading3: 'Heading 3',
  heading4: 'Heading 4',
  paragraph: 'Paragraph',
  list: 'List',
  bulletList: 'Bullet List',
  orderedList: 'Ordered List',
  taskList: 'Task List',
  blockquote: 'Blockquote',
  codeBlock: 'Code Block',
  bold: 'Bold',
  italic: 'Italic',
  strike: 'Strikethrough',
  code: 'Code',
  underline: 'Underline',
  highlight: 'Highlight',
  removeHighlight: 'Remove Highlight',
  link: 'Link',
  linkPlaceholder: 'Paste a link...',
  applyLink: 'Apply',
  openLink: 'Open in new window',
  removeLink: 'Remove link',
  superscript: 'Superscript',
  subscript: 'Subscript',
  alignLeft: 'Align Left',
  alignCenter: 'Align Center',
  alignRight: 'Align Right',
  alignJustify: 'Justify',
  insertImage: 'Insert Image',
  uploadImage: 'Upload Image',
  clickToUpload: 'Click to upload',
  orDragAndDrop: 'or drag and drop',
  maxFiles: 'Maximum {limit} file(s), {size}MB each',
  clearAll: 'Clear All',
};

// ============================================================================
// Props Types
// ============================================================================

/**
 * Send keymap configuration
 */
export type SendKeymap = 'enter' | 'ctrlEnter' | 'cmdEnter';

/**
 * Editor mode
 */
export type EditorMode = 'plain' | 'rich';

/**
 * Attachment limit exceeded reason
 */
export type AttachmentLimitReason = 'count' | 'size' | 'mime';

/**
 * Main component props
 */
export interface IMComposerProps {
  // Mode
  /** Controlled mode */
  mode?: EditorMode;
  /** Default mode for uncontrolled usage */
  defaultMode?: EditorMode;

  // Callbacks
  /** Called when user triggers send action */
  onSend?: (payload: PlainMessagePayload | MarkdownMessagePayload) => void;
  /** Called when editor content changes */
  onChange?: () => void;
  /** Context menu handler */
  onContextMenu?: MouseEventHandler<HTMLDivElement>;
  /** Called when quote is removed */
  onQuoteRemoved?: () => void;

  // Plain Mode - Mention
  /** Enable @mention feature */
  enableMention?: boolean;
  /** Async provider for mention suggestions */
  mentionProvider?: (query: string) => Promise<Member[]>;
  /** Maximum number of mentions allowed */
  maxMentions?: number;
  /** Called when mention limit is exceeded */
  onMentionLimitExceeded?: () => void;
  /** Custom render function for mention list items */
  renderMentionItem?: (props: { member: Member; isSelected: boolean }) => ReactNode;
  /** Mention list placement relative to cursor: 'top' or 'bottom' */
  mentionPlacement?: 'top' | 'bottom';

  // Plain Mode - Attachments
  /** Enable file attachments */
  enableAttachments?: boolean;
  /** Attachment preview bar placement */
  attachmentPreviewPlacement?: 'top' | 'bottom';
  /** Maximum number of attachments */
  maxAttachments?: number;
  /** Allowed MIME types (supports wildcards like "image/*") */
  allowedMimeTypes?: string[];
  /** Maximum file size in bytes */
  maxFileSize?: number;
  /** Called when attachment limit is exceeded */
  onAttachmentLimitExceeded?: (reason: AttachmentLimitReason, file: File) => void;
  /** Called when attachments change */
  onFilesChange?: (attachments: Attachment[]) => void;
  /** Show attachment preview bar */
  showAttachmentPreview?: boolean;

  // Rich Mode
  /** Markdown options */
  markdownOptions?: {
    enabledSyntax?: string[];
  };
  /** Image upload handler with optional progress callback */
  uploadImage?: UploadImageFn;
  /** Rich mode toolbar configuration */
  richToolbarConfig?: {
    undoRedo?: boolean;
    heading?: boolean;
    list?: boolean;
    blockquote?: boolean;
    codeBlock?: boolean;
    bold?: boolean;
    italic?: boolean;
    strike?: boolean;
    code?: boolean;
    underline?: boolean;
    highlight?: boolean;
    link?: boolean;
    superscript?: boolean;
    subscript?: boolean;
    textAlign?: boolean;
    image?: boolean;
  };

  // Keymap
  /** Keymap configuration */
  keymap?: {
    send?: SendKeymap;
  };

  // Common
  /** Placeholder text (string or per-mode object) */
  placeholder?: string | { plain?: string; rich?: string };
  /** Disable the editor */
  disabled?: boolean;
  /** Additional CSS class */
  className?: string;

  // i18n
  /** Locale strings */
  locale?: IMComposerLocale;
}

// ============================================================================
// Ref Types
// ============================================================================

/**
 * Methods exposed via ref
 */
export interface IMComposerRef {
  /** Focus the editor */
  focus: () => void;
  /** Clear the editor content */
  clear: () => void;
  /** Export current content as payload. Returns null if empty or uploading */
  exportPayload: () => PlainMessagePayload | MarkdownMessagePayload | null;

  // Rich mode
  /** Import markdown content (rich mode only) */
  importMarkdown: (markdown: string) => void;

  // Attachments (plain mode only)
  /** Get current attachments */
  getAttachments: () => Attachment[];
  /** Set attachments */
  setAttachments: (attachments: Attachment[]) => void;
  /** Add files to attachments */
  addFiles: (files: FileList | File[]) => void;
  /** Remove a specific attachment by ID */
  removeAttachment: (id: string) => void;
  /** Clear all attachments */
  clearAttachments: () => void;

  // Quote (plain mode only)
  /** Insert or replace a quote */
  insertQuote: (title: string, content: string) => void;

  // Mention (plain mode only)
  /** Programmatically insert a mention */
  insertMention: (userId: string, display: string) => void;

  // Draft
  /** Get current draft state */
  getDraft: () => ComposerDraft;
  /** Restore from draft state */
  setDraft: (draft: ComposerDraft) => void;

  // Text operations
  /** Set text content (with optional mentions for plain mode) */
  setText: (text: string, mentions?: Member[]) => void;
  /** Insert text at cursor */
  insertText: (text: string) => void;
}

// ============================================================================
// Internal Types (not exported from main entry)
// ============================================================================

/**
 * @internal Mention suggestion state
 */
export interface MentionSuggestionState {
  active: boolean;
  query: string;
  items: Member[];
  selectedIndex: number;
  loading: boolean;
  error: boolean;
  /** Command to insert a mention (replaces @ trigger) */
  command: ((member: { userId: string; display: string }) => void) | null;
}

/**
 * @internal Composition state for IME handling
 */
export interface CompositionState {
  isComposing: boolean;
}

/**
 * @internal Upload state for images
 */
export interface UploadState {
  uploadingCount: number;
}
