// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.0
// source: openmeeting/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password"`
	FaceURL       string                 `protobuf:"bytes,50,opt,name=faceURL,proto3" json:"faceURL"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_openmeeting_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_openmeeting_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_openmeeting_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

var File_openmeeting_user_user_proto protoreflect.FileDescriptor

const file_openmeeting_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1bopenmeeting/user/user.proto\x12\x10openmeeting.user\"\x8e\x01\n" +
	"\bUserInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x18\n" +
	"\afaceURL\x182 \x01(\tR\afaceURLB0Z.github.com/openimsdk/protocol/openmeeting/userb\x06proto3"

var (
	file_openmeeting_user_user_proto_rawDescOnce sync.Once
	file_openmeeting_user_user_proto_rawDescData []byte
)

func file_openmeeting_user_user_proto_rawDescGZIP() []byte {
	file_openmeeting_user_user_proto_rawDescOnce.Do(func() {
		file_openmeeting_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmeeting_user_user_proto_rawDesc), len(file_openmeeting_user_user_proto_rawDesc)))
	})
	return file_openmeeting_user_user_proto_rawDescData
}

var file_openmeeting_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_openmeeting_user_user_proto_goTypes = []any{
	(*UserInfo)(nil), // 0: openmeeting.user.UserInfo
}
var file_openmeeting_user_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openmeeting_user_user_proto_init() }
func file_openmeeting_user_user_proto_init() {
	if File_openmeeting_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmeeting_user_user_proto_rawDesc), len(file_openmeeting_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmeeting_user_user_proto_goTypes,
		DependencyIndexes: file_openmeeting_user_user_proto_depIdxs,
		MessageInfos:      file_openmeeting_user_user_proto_msgTypes,
	}.Build()
	File_openmeeting_user_user_proto = out.File
	file_openmeeting_user_user_proto_goTypes = nil
	file_openmeeting_user_user_proto_depIdxs = nil
}
