// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.26.0
// source: encryption/encryption.proto

package encryption

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Encryption_GetEncryptionKey_FullMethodName = "/openim.encryption.encryption/GetEncryptionKey"
	Encryption_GenEncryptionKey_FullMethodName = "/openim.encryption.encryption/GenEncryptionKey"
)

// EncryptionClient is the client API for Encryption service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncryptionClient interface {
	// rpc EncryptContent(EncryptContentReq)returns(EncryptContentResp);
	GetEncryptionKey(ctx context.Context, in *GetEncryptionKeyReq, opts ...grpc.CallOption) (*GetEncryptionKeyResp, error)
	GenEncryptionKey(ctx context.Context, in *GenEncryptionKeyReq, opts ...grpc.CallOption) (*GenEncryptionKeyResp, error)
}

type encryptionClient struct {
	cc grpc.ClientConnInterface
}

func NewEncryptionClient(cc grpc.ClientConnInterface) EncryptionClient {
	return &encryptionClient{cc}
}

func (c *encryptionClient) GetEncryptionKey(ctx context.Context, in *GetEncryptionKeyReq, opts ...grpc.CallOption) (*GetEncryptionKeyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEncryptionKeyResp)
	err := c.cc.Invoke(ctx, Encryption_GetEncryptionKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionClient) GenEncryptionKey(ctx context.Context, in *GenEncryptionKeyReq, opts ...grpc.CallOption) (*GenEncryptionKeyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenEncryptionKeyResp)
	err := c.cc.Invoke(ctx, Encryption_GenEncryptionKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncryptionServer is the server API for Encryption service.
// All implementations must embed UnimplementedEncryptionServer
// for forward compatibility.
type EncryptionServer interface {
	// rpc EncryptContent(EncryptContentReq)returns(EncryptContentResp);
	GetEncryptionKey(context.Context, *GetEncryptionKeyReq) (*GetEncryptionKeyResp, error)
	GenEncryptionKey(context.Context, *GenEncryptionKeyReq) (*GenEncryptionKeyResp, error)
	mustEmbedUnimplementedEncryptionServer()
}

// UnimplementedEncryptionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEncryptionServer struct{}

func (UnimplementedEncryptionServer) GetEncryptionKey(context.Context, *GetEncryptionKeyReq) (*GetEncryptionKeyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEncryptionKey not implemented")
}
func (UnimplementedEncryptionServer) GenEncryptionKey(context.Context, *GenEncryptionKeyReq) (*GenEncryptionKeyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenEncryptionKey not implemented")
}
func (UnimplementedEncryptionServer) mustEmbedUnimplementedEncryptionServer() {}
func (UnimplementedEncryptionServer) testEmbeddedByValue()                    {}

// UnsafeEncryptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncryptionServer will
// result in compilation errors.
type UnsafeEncryptionServer interface {
	mustEmbedUnimplementedEncryptionServer()
}

func RegisterEncryptionServer(s grpc.ServiceRegistrar, srv EncryptionServer) {
	// If the following call panics, it indicates UnimplementedEncryptionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Encryption_ServiceDesc, srv)
}

func _Encryption_GetEncryptionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEncryptionKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServer).GetEncryptionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Encryption_GetEncryptionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServer).GetEncryptionKey(ctx, req.(*GetEncryptionKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Encryption_GenEncryptionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenEncryptionKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServer).GenEncryptionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Encryption_GenEncryptionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServer).GenEncryptionKey(ctx, req.(*GenEncryptionKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Encryption_ServiceDesc is the grpc.ServiceDesc for Encryption service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Encryption_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.encryption.encryption",
	HandlerType: (*EncryptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEncryptionKey",
			Handler:    _Encryption_GetEncryptionKey_Handler,
		},
		{
			MethodName: "GenEncryptionKey",
			Handler:    _Encryption_GenEncryptionKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encryption/encryption.proto",
}
