// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.26.0
// source: openmeeting/signal/signal.proto

package signal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Signal_SignalMessageAssemble_FullMethodName           = "/openmeeting.signal.Signal/SignalMessageAssemble"
	Signal_SignalGetRoomByGroupID_FullMethodName          = "/openmeeting.signal.Signal/SignalGetRoomByGroupID"
	Signal_SignalGetTokenByRoomID_FullMethodName          = "/openmeeting.signal.Signal/SignalGetTokenByRoomID"
	Signal_SignalGetRooms_FullMethodName                  = "/openmeeting.signal.Signal/SignalGetRooms"
	Signal_GetSignalInvitationInfo_FullMethodName         = "/openmeeting.signal.Signal/GetSignalInvitationInfo"
	Signal_GetSignalInvitationInfoStartApp_FullMethodName = "/openmeeting.signal.Signal/GetSignalInvitationInfoStartApp"
	Signal_GetSignalInvitationRecords_FullMethodName      = "/openmeeting.signal.Signal/GetSignalInvitationRecords"
	Signal_DeleteSignalRecords_FullMethodName             = "/openmeeting.signal.Signal/DeleteSignalRecords"
	Signal_GetUserSignalRecord_FullMethodName             = "/openmeeting.signal.Signal/GetUserSignalRecord"
)

// SignalClient is the client API for Signal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalClient interface {
	SignalMessageAssemble(ctx context.Context, in *SignalMessageAssembleReq, opts ...grpc.CallOption) (*SignalMessageAssembleResp, error)
	SignalGetRoomByGroupID(ctx context.Context, in *SignalGetRoomByGroupIDReq, opts ...grpc.CallOption) (*SignalGetRoomByGroupIDResp, error)
	SignalGetTokenByRoomID(ctx context.Context, in *SignalGetTokenByRoomIDReq, opts ...grpc.CallOption) (*SignalGetTokenByRoomIDResp, error)
	SignalGetRooms(ctx context.Context, in *SignalGetRoomsReq, opts ...grpc.CallOption) (*SignalGetRoomsResp, error)
	GetSignalInvitationInfo(ctx context.Context, in *GetSignalInvitationInfoReq, opts ...grpc.CallOption) (*GetSignalInvitationInfoResp, error)
	GetSignalInvitationInfoStartApp(ctx context.Context, in *GetSignalInvitationInfoStartAppReq, opts ...grpc.CallOption) (*GetSignalInvitationInfoStartAppResp, error)
	GetSignalInvitationRecords(ctx context.Context, in *GetSignalInvitationRecordsReq, opts ...grpc.CallOption) (*GetSignalInvitationRecordsResp, error)
	DeleteSignalRecords(ctx context.Context, in *DeleteSignalRecordsReq, opts ...grpc.CallOption) (*DeleteSignalRecordsResp, error)
	GetUserSignalRecord(ctx context.Context, in *GetUserSignalRecordReq, opts ...grpc.CallOption) (*GetUserSignalRecordResp, error)
}

type signalClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalClient(cc grpc.ClientConnInterface) SignalClient {
	return &signalClient{cc}
}

func (c *signalClient) SignalMessageAssemble(ctx context.Context, in *SignalMessageAssembleReq, opts ...grpc.CallOption) (*SignalMessageAssembleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalMessageAssembleResp)
	err := c.cc.Invoke(ctx, Signal_SignalMessageAssemble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalClient) SignalGetRoomByGroupID(ctx context.Context, in *SignalGetRoomByGroupIDReq, opts ...grpc.CallOption) (*SignalGetRoomByGroupIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalGetRoomByGroupIDResp)
	err := c.cc.Invoke(ctx, Signal_SignalGetRoomByGroupID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalClient) SignalGetTokenByRoomID(ctx context.Context, in *SignalGetTokenByRoomIDReq, opts ...grpc.CallOption) (*SignalGetTokenByRoomIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalGetTokenByRoomIDResp)
	err := c.cc.Invoke(ctx, Signal_SignalGetTokenByRoomID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalClient) SignalGetRooms(ctx context.Context, in *SignalGetRoomsReq, opts ...grpc.CallOption) (*SignalGetRoomsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalGetRoomsResp)
	err := c.cc.Invoke(ctx, Signal_SignalGetRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalClient) GetSignalInvitationInfo(ctx context.Context, in *GetSignalInvitationInfoReq, opts ...grpc.CallOption) (*GetSignalInvitationInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignalInvitationInfoResp)
	err := c.cc.Invoke(ctx, Signal_GetSignalInvitationInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalClient) GetSignalInvitationInfoStartApp(ctx context.Context, in *GetSignalInvitationInfoStartAppReq, opts ...grpc.CallOption) (*GetSignalInvitationInfoStartAppResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignalInvitationInfoStartAppResp)
	err := c.cc.Invoke(ctx, Signal_GetSignalInvitationInfoStartApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalClient) GetSignalInvitationRecords(ctx context.Context, in *GetSignalInvitationRecordsReq, opts ...grpc.CallOption) (*GetSignalInvitationRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignalInvitationRecordsResp)
	err := c.cc.Invoke(ctx, Signal_GetSignalInvitationRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalClient) DeleteSignalRecords(ctx context.Context, in *DeleteSignalRecordsReq, opts ...grpc.CallOption) (*DeleteSignalRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSignalRecordsResp)
	err := c.cc.Invoke(ctx, Signal_DeleteSignalRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalClient) GetUserSignalRecord(ctx context.Context, in *GetUserSignalRecordReq, opts ...grpc.CallOption) (*GetUserSignalRecordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSignalRecordResp)
	err := c.cc.Invoke(ctx, Signal_GetUserSignalRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignalServer is the server API for Signal service.
// All implementations must embed UnimplementedSignalServer
// for forward compatibility.
type SignalServer interface {
	SignalMessageAssemble(context.Context, *SignalMessageAssembleReq) (*SignalMessageAssembleResp, error)
	SignalGetRoomByGroupID(context.Context, *SignalGetRoomByGroupIDReq) (*SignalGetRoomByGroupIDResp, error)
	SignalGetTokenByRoomID(context.Context, *SignalGetTokenByRoomIDReq) (*SignalGetTokenByRoomIDResp, error)
	SignalGetRooms(context.Context, *SignalGetRoomsReq) (*SignalGetRoomsResp, error)
	GetSignalInvitationInfo(context.Context, *GetSignalInvitationInfoReq) (*GetSignalInvitationInfoResp, error)
	GetSignalInvitationInfoStartApp(context.Context, *GetSignalInvitationInfoStartAppReq) (*GetSignalInvitationInfoStartAppResp, error)
	GetSignalInvitationRecords(context.Context, *GetSignalInvitationRecordsReq) (*GetSignalInvitationRecordsResp, error)
	DeleteSignalRecords(context.Context, *DeleteSignalRecordsReq) (*DeleteSignalRecordsResp, error)
	GetUserSignalRecord(context.Context, *GetUserSignalRecordReq) (*GetUserSignalRecordResp, error)
	mustEmbedUnimplementedSignalServer()
}

// UnimplementedSignalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignalServer struct{}

func (UnimplementedSignalServer) SignalMessageAssemble(context.Context, *SignalMessageAssembleReq) (*SignalMessageAssembleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalMessageAssemble not implemented")
}
func (UnimplementedSignalServer) SignalGetRoomByGroupID(context.Context, *SignalGetRoomByGroupIDReq) (*SignalGetRoomByGroupIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalGetRoomByGroupID not implemented")
}
func (UnimplementedSignalServer) SignalGetTokenByRoomID(context.Context, *SignalGetTokenByRoomIDReq) (*SignalGetTokenByRoomIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalGetTokenByRoomID not implemented")
}
func (UnimplementedSignalServer) SignalGetRooms(context.Context, *SignalGetRoomsReq) (*SignalGetRoomsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalGetRooms not implemented")
}
func (UnimplementedSignalServer) GetSignalInvitationInfo(context.Context, *GetSignalInvitationInfoReq) (*GetSignalInvitationInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignalInvitationInfo not implemented")
}
func (UnimplementedSignalServer) GetSignalInvitationInfoStartApp(context.Context, *GetSignalInvitationInfoStartAppReq) (*GetSignalInvitationInfoStartAppResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignalInvitationInfoStartApp not implemented")
}
func (UnimplementedSignalServer) GetSignalInvitationRecords(context.Context, *GetSignalInvitationRecordsReq) (*GetSignalInvitationRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignalInvitationRecords not implemented")
}
func (UnimplementedSignalServer) DeleteSignalRecords(context.Context, *DeleteSignalRecordsReq) (*DeleteSignalRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSignalRecords not implemented")
}
func (UnimplementedSignalServer) GetUserSignalRecord(context.Context, *GetUserSignalRecordReq) (*GetUserSignalRecordResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSignalRecord not implemented")
}
func (UnimplementedSignalServer) mustEmbedUnimplementedSignalServer() {}
func (UnimplementedSignalServer) testEmbeddedByValue()                {}

// UnsafeSignalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalServer will
// result in compilation errors.
type UnsafeSignalServer interface {
	mustEmbedUnimplementedSignalServer()
}

func RegisterSignalServer(s grpc.ServiceRegistrar, srv SignalServer) {
	// If the following call panics, it indicates UnimplementedSignalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Signal_ServiceDesc, srv)
}

func _Signal_SignalMessageAssemble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalMessageAssembleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).SignalMessageAssemble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_SignalMessageAssemble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).SignalMessageAssemble(ctx, req.(*SignalMessageAssembleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signal_SignalGetRoomByGroupID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalGetRoomByGroupIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).SignalGetRoomByGroupID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_SignalGetRoomByGroupID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).SignalGetRoomByGroupID(ctx, req.(*SignalGetRoomByGroupIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signal_SignalGetTokenByRoomID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalGetTokenByRoomIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).SignalGetTokenByRoomID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_SignalGetTokenByRoomID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).SignalGetTokenByRoomID(ctx, req.(*SignalGetTokenByRoomIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signal_SignalGetRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalGetRoomsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).SignalGetRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_SignalGetRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).SignalGetRooms(ctx, req.(*SignalGetRoomsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signal_GetSignalInvitationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignalInvitationInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).GetSignalInvitationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_GetSignalInvitationInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).GetSignalInvitationInfo(ctx, req.(*GetSignalInvitationInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signal_GetSignalInvitationInfoStartApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignalInvitationInfoStartAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).GetSignalInvitationInfoStartApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_GetSignalInvitationInfoStartApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).GetSignalInvitationInfoStartApp(ctx, req.(*GetSignalInvitationInfoStartAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signal_GetSignalInvitationRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignalInvitationRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).GetSignalInvitationRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_GetSignalInvitationRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).GetSignalInvitationRecords(ctx, req.(*GetSignalInvitationRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signal_DeleteSignalRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSignalRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).DeleteSignalRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_DeleteSignalRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).DeleteSignalRecords(ctx, req.(*DeleteSignalRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signal_GetUserSignalRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSignalRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServer).GetUserSignalRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signal_GetUserSignalRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServer).GetUserSignalRecord(ctx, req.(*GetUserSignalRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Signal_ServiceDesc is the grpc.ServiceDesc for Signal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openmeeting.signal.Signal",
	HandlerType: (*SignalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignalMessageAssemble",
			Handler:    _Signal_SignalMessageAssemble_Handler,
		},
		{
			MethodName: "SignalGetRoomByGroupID",
			Handler:    _Signal_SignalGetRoomByGroupID_Handler,
		},
		{
			MethodName: "SignalGetTokenByRoomID",
			Handler:    _Signal_SignalGetTokenByRoomID_Handler,
		},
		{
			MethodName: "SignalGetRooms",
			Handler:    _Signal_SignalGetRooms_Handler,
		},
		{
			MethodName: "GetSignalInvitationInfo",
			Handler:    _Signal_GetSignalInvitationInfo_Handler,
		},
		{
			MethodName: "GetSignalInvitationInfoStartApp",
			Handler:    _Signal_GetSignalInvitationInfoStartApp_Handler,
		},
		{
			MethodName: "GetSignalInvitationRecords",
			Handler:    _Signal_GetSignalInvitationRecords_Handler,
		},
		{
			MethodName: "DeleteSignalRecords",
			Handler:    _Signal_DeleteSignalRecords_Handler,
		},
		{
			MethodName: "GetUserSignalRecord",
			Handler:    _Signal_GetUserSignalRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openmeeting/signal/signal.proto",
}
